/* AKSI Core v5 — local-first. Network is explicit opt-in. Integrity is not truth. */
window.AksiCore=(function(){'use strict';
var NET='AKSI_NET_V1',DREAMS='AKSI_DREAMS_V1',MEM='AKSI_CORE_MEM',LEDGER='AKSI_CORE_LEDGER_V5',IDDB='AKSI_IDENTITY_V1',WEB='AKSI_WEB_ALLOWED_V1';
function load(k,fb){try{var v=JSON.parse(localStorage.getItem(k)||'null');return v==null?fb:v}catch(e){return fb}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(function(k){return JSON.stringify(k)+':'+canonical(v[k])}).join(',')+'}'}
async function sha(v){var s=typeof v==='string'?v:canonical(v),b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
function saveMem(role,text,meta){var m=load(MEM,[]);m.push({role:role,text:String(text).slice(0,4000),meta:meta||{},t:new Date().toISOString()});save(MEM,m.slice(-500))}
function memory(q){var m=load(MEM,[]);if(!q)return m.slice().reverse();var words=String(q).toLowerCase().split(/\s+/).filter(function(x){return x.length>2});return m.filter(function(x){var s=x.text.toLowerCase();return words.some(function(w){return s.indexOf(w)>=0})}).slice(-30).reverse()}
function idOpen(){return new Promise(function(resolve,reject){if(!indexedDB)return reject(new Error('IndexedDB unavailable'));var r=indexedDB.open(IDDB,1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains('keys'))r.result.createObjectStore('keys')};r.onsuccess=function(){resolve(r.result)};r.onerror=function(){reject(r.error)}})}
function idGet(k){return idOpen().then(function(db){return new Promise(function(res,rej){var t=db.transaction('keys','readonly'),q=t.objectStore('keys').get(k);q.onsuccess=function(){res(q.result||null)};q.onerror=function(){rej(q.error)}})})}
function idPut(k,v){return idOpen().then(function(db){return new Promise(function(res,rej){var t=db.transaction('keys','readwrite'),q=t.objectStore('keys').put(v,k);q.onsuccess=function(){res(v)};q.onerror=function(){rej(q.error)}})})}
async function identity(){try{var existing=await idGet('identity');if(existing&&existing.privateKey&&existing.publicJwk)return{algorithm:'Ed25519',publicKey:existing.publicJwk,createdAt:existing.createdAt,secureStorage:true};var kp=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']);var pub=await crypto.subtle.exportKey('jwk',kp.publicKey);await idPut('identity',{privateKey:kp.privateKey,publicJwk:pub,createdAt:new Date().toISOString()});return{algorithm:'Ed25519',publicKey:pub,createdAt:new Date().toISOString(),secureStorage:true}}catch(e){return{available:false,reason:String(e.message||e),secureStorage:false}}}
async function sign(data){var x=await idGet('identity');if(!x||!x.privateKey)throw new Error('identity unavailable');var b=await crypto.subtle.sign({name:'Ed25519'},x.privateKey,new TextEncoder().encode(typeof data==='string'?data:canonical(data)));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
async function fingerprint(){var x=await identity();return x.available===false?'unavailable':(await sha(x.publicKey)).slice(0,32)}
async function append(type,subject,source,status,extra){var l=load(LEDGER,[]),previous=l.length?l[l.length-1].event_hash:'GENESIS',body={schema:'AKSI-EVENT-5',type:type,subject:String(subject),source:source||'local',status:status||'unverified',created_at:new Date().toISOString(),previous_hash:previous,extra:extra||null};var e=Object.assign({},body,{event_hash:await sha(body)});l.push(e);save(LEDGER,l.slice(-1000));return e}
async function verify(){var l=load(LEDGER,[]),previous='GENESIS';for(var i=0;i<l.length;i++){var e=l[i],body={schema:e.schema,type:e.type,subject:e.subject,source:e.source,status:e.status,created_at:e.created_at,previous_hash:previous,extra:e.extra||null};if(e.previous_hash!==previous||e.event_hash!==await sha(body))return{ok:false,index:i,reason:'tamper-detected'};previous=e.event_hash}return{ok:true,count:l.length,head:previous}}
function score(blob,words){var s=0;words.forEach(function(w){if(w.length>1&&blob.indexOf(w)>=0)s+=w.length>3?2:1});return s}
function fromNet(q){var pages=load(NET,[]);if(!Array.isArray(pages)||!pages.length)return null;var words=q.toLowerCase().split(/\s+/),best=null,bestS=0;pages.forEach(function(p){var blob=((p.title||'')+' '+(p.body||'')+' '+(p.tags||[]).join(' ')).toLowerCase(),s=score(blob,words);if((p.title||'').toLowerCase().indexOf(q.toLowerCase())>=0)s+=5;if(s>bestS){bestS=s;best=p}});return best&&bestS>=2?{text:best.body,source:'Локальная сеть · '+best.title,status:'observed'}:null}
function fromDreams(q){if(!/сон|снилось|сновид/.test(q))return null;var d=load(DREAMS,[]);return d[0]?{text:d[0].text,source:'Локальный журнал сна',status:'observed'}:{text:'Снов ещё нет.',source:null,status:'computed'}}
function fromCore(q){if(!window.AKSIKnowledge)return null;var p=AKSIKnowledge.search(q);return p?{text:p.title+'.\n\n'+p.body,source:'Локальная база',status:'computed'}:null}
function rules(q){var low=q.toLowerCase();if(/^(привет|здравств|добрый|hello)/.test(low))return{text:'Здравствуйте. Я АКСИ. Я разделяю вычисленное, наблюдаемое и непроверенное.',source:null,status:'computed'};if(/кто ты|как тебя зовут/.test(low))return{text:'Я АКСИ — локальный когнитивный контур. Моя программная идентичность отделена от содержания ответов.',source:'Идентичность',status:'computed'};if(/помощ|help|что умеешь|функц/.test(low))return{text:'Чат, локальная память, Proof, Identity и экспериментальные инструменты. Интернет отключён по умолчанию и включается отдельно.',source:'Справка',status:'computed'};if(/доказ|proof|чест|провер/.test(low))return{text:'Proof проверяет целостность записи. Это не доказательство истинности внешнего утверждения.',source:'Trust',status:'computed'};return null}
async function wiki(q){if(!load(WEB,false)||!navigator.onLine)return null;try{var query=q.replace(/^(что такое|кто такой|расскажи про|почему)\s+/i,'').trim();if(query.length<2)return null;var c=new AbortController(),t=setTimeout(function(){c.abort()},3500),s=await fetch('https://ru.wikipedia.org/w/api.php?action=opensearch&search='+encodeURIComponent(query)+'&limit=1&namespace=0&format=json&origin=*',{signal:c.signal}).then(function(r){return r.json()});clearTimeout(t);var title=s&&s[1]&&s[1][0];if(!title)return null;var j=await fetch('https://ru.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(title)).then(function(r){return r.json()});return j&&j.extract?{text:j.title+'.\n\n'+String(j.extract).slice(0,900),source:'Wikipedia',status:'observed'}:null}catch(e){return null}}
async function reply(userText){var q=String(userText||'').trim();if(!q)return{text:'Напишите вопрос.',source:null,status:'computed'};saveMem('user',q,{source:'user'});var a=rules(q)||fromDreams(q)||fromNet(q)||fromCore(q)||await wiki(q)||{text:load(WEB,false)&&navigator.onLine?'Не нашла точного ответа в доступных источниках.':'Офлайн: точного ответа в доступных локальных источниках нет.',source:null,status:'unverified'};saveMem('aksi',a.text,{source:a.source,status:a.status});var e=await append('cognitive-response',a.text,a.source||'local',a.status||'unverified',{query:q,networkEnabled:load(WEB,false)});return Object.assign({},a,{event:e})}
async function selfTest(){var h=await sha({aksi:'core',version:'5'}),v=await verify(),id=await identity();return{ok:!!h&&v.ok,hash:h.slice(0,16),ledger:v.count,identity:await fingerprint(),secureIdentity:!!id.secureStorage,version:'5.0.0',webEnabled:load(WEB,false)}}
return{reply:reply,saveMem:saveMem,memory:memory,canonical:canonical,sha:sha,identity:identity,sign:sign,fingerprint:fingerprint,append:append,verify:verify,selfTest:selfTest,webEnabled:function(){return load(WEB,false)},setWebEnabled:function(v){save(WEB,!!v);return!!v},exportState:function(){return{schema:'AKSI-STATE-5',memory:load(MEM,[]),ledger:load(LEDGER,[]),webEnabled:load(WEB,false),exportedAt:new Date().toISOString()}}}})();
