/** AKSI Runtime Contract v1.4 — local-first orchestration + cognitive/quantum/proof hooks. */
(function(g){'use strict';
var V='1.4.0';
function canonical(v){if(v===undefined)return'null';if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).filter(function(k){return v[k]!==undefined&&typeof v[k]!=='function';}).sort().map(function(k){return JSON.stringify(k)+':'+canonical(v[k]);}).join(',')+'}';}
function provider(name,globals,methods){for(var i=0;i<globals.length;i++){var x=g[globals[i]];if(x)return{name:name,global:globals[i],available:true,ready:methods.some(function(m){return typeof x[m]==='function'}),object:x};}return{name:name,available:false,ready:false};}
function status(){var p={local:provider('local',['AKSI_LOCAL_ENGINE','AKSILocalEngine'],['ask','generate']),core:provider('core',['AKSI_CORE'],['query']),metrics:provider('metrics',['AKSI_METRICS'],['measure']),proof:provider('proof',['AKSIProof'],['add']),quantum:provider('quantum',['AKSIQuantum'],['run']),cognitive:provider('cognitive',['AKSICognitive'],['run'])};return{schema:'AKSI-RUNTIME-1',version:V,runtime:(p.local.ready||p.core.ready)?'ready':'degraded',timestamp:Date.now(),providers:Object.keys(p).reduce(function(o,k){var x=p[k];o[k]={name:x.name,global:x.global||null,available:x.available,ready:x.ready};return o;},{}),integrity:{crypto:!!(g.crypto&&g.crypto.subtle)}};}
async function sha256(v){if(!g.crypto||!g.crypto.subtle)throw Error('WebCrypto unavailable');var d=await g.crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d)).map(function(x){return x.toString(16).padStart(2,'0')}).join('');}
function answer(input,text,meta){meta=meta||{};return{schema:'AKSI-ANSWER-1',input:String(input||''),text:String(text||''),source:String(meta.source||'unknown'),kind:String(meta.kind||'unverified'),confidence:typeof meta.confidence==='number'?Math.max(0,Math.min(1,meta.confidence)):null,citations:Array.isArray(meta.citations)?meta.citations.slice(0,20):[],generatedAt:Date.now()};}
async function execute(input,opts){opts=opts||{};var q=String(input||'').trim();if(!q)throw Error('Empty input');var started=performance.now(),events=[];function ev(type,data){events.push({type:type,data:data||{},at:Date.now()});try{g.dispatchEvent(new CustomEvent('aksi:runtime-trace',{detail:events[events.length-1]}));}catch(_){} }
ev('input.received',{chars:q.length});var result=null;
if(opts.cognitive!==false&&g.AKSICognitive&&typeof g.AKSICognitive.run==='function'){ev('route.cognitive');var cr=await g.AKSICognitive.run(q,opts);if(cr&&cr.ok!==false){var ca=answer(q,cr.answer,{source:'local-cognitive',kind:'local'});ca.cognitive=cr;ca.metrics=g.AKSI_METRICS&&typeof g.AKSI_METRICS.measure==='function'?g.AKSI_METRICS.measure({input:q,output:ca.text,meta:{uncertainty:cr.selected&&cr.selected.uncertainty||.5,memoryHits:cr.selected&&cr.selected.evidence?cr.selected.evidence.length:0},trace:cr.trace}):null;ca.trace=cr.trace;ca.latencyMs=Math.round(performance.now()-started);ca.integrityHash=await sha256(ca);ev('verification.complete',{hash:ca.integrityHash,latencyMs:ca.latencyMs});return ca;}}
var E=g.AKSI_LOCAL_ENGINE||g.AKSILocalEngine;
if(E&&typeof E.ask==='function'){ev('route.local.ask');result=await E.ask(q,opts);}
else if(E&&typeof E.generate==='function'){ev('route.local.generate');result=await E.generate([{role:'user',content:q}],opts);}
else if(g.AKSI_CORE&&typeof g.AKSI_CORE.query==='function'){ev('route.core');result=await g.AKSI_CORE.query(q,{allowNetwork:opts.allowNetwork===true});}
else throw Error('No AKSI provider available');
ev('answer.received',{source:result&&result.source||'local',chars:String(result&&result.text||'').length});var a=answer(q,result&&result.text,{source:result&&result.source||'local',kind:result&&result.offline?'local':'unverified',citations:result&&result.sources||[]});a.metrics=g.AKSI_METRICS&&typeof g.AKSI_METRICS.measure==='function'?g.AKSI_METRICS.measure({input:q,output:a.text,meta:result&&result.metrics||{},trace:events}):null;a.trace=events;a.latencyMs=Math.round(performance.now()-started);a.integrityHash=await sha256(a);ev('verification.complete',{hash:a.integrityHash,latencyMs:a.latencyMs});return a;}
async function selfTest(){var s=status(),proof=false;try{proof=(await sha256({test:'AKSI',version:V})).length===64;}catch(e){}return{ok:(s.runtime==='ready')&&s.integrity.crypto,version:V,status:s,sha256:proof};}
g.AKSI_RUNTIME={version:V,status:status,answer:answer,canonical:canonical,sha256:sha256,execute:execute,selfTest:selfTest};
})(typeof window!=='undefined'?window:this);