(()=>{'use strict';
/* AKSI PROOF LEDGER v2 — local SHA-256 integrity + Ed25519 signatures. */
const DB='AKSI_PROOF_V2',STATE='state',LOG='ledger';
const stable=v=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const bytes=s=>new TextEncoder().encode(stable(s));
const subtle=()=>{if(!crypto?.subtle)throw Error('WebCrypto unavailable');return crypto.subtle};
function open(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STATE))d.createObjectStore(STATE,{keyPath:'id'});if(!d.objectStoreNames.contains(LOG))d.createObjectStore(LOG,{keyPath:'seq'});};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function readState(){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STATE,'readonly').objectStore(STATE).get('identity');r.onsuccess=()=>{d.close();ok(r.result||null)};r.onerror=()=>{d.close();no(r.error)}})}
async function writeState(v){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(STATE,'readwrite').objectStore(STATE).put(v);r.onsuccess=()=>{d.close();ok(v)};r.onerror=()=>{d.close();no(r.error)}})}
async function history(){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(LOG,'readonly').objectStore(LOG).getAll();r.onsuccess=()=>{d.close();ok((r.result||[]).sort((a,b)=>a.seq-b.seq))};r.onerror=()=>{d.close();no(r.error)}})}
async function write(v){const d=await open();return new Promise((ok,no)=>{const r=d.transaction(LOG,'readwrite').objectStore(LOG).put(v);r.onsuccess=()=>{d.close();ok(v)};r.onerror=()=>{d.close();no(r.error)}})}
async function identity(){let s=await readState();if(s)return s;let kp;try{kp=await subtle().generateKey({name:'Ed25519'},true,['sign','verify'])}catch(e){throw Error('Ed25519 unavailable: '+e.message)}s={id:'identity',created_at:new Date().toISOString(),public_key:await subtle().exportKey('jwk',kp.publicKey),private_key:kp.privateKey};await writeState(s);return s}
async function digest(value){return hex(await subtle().digest('SHA-256',new TextEncoder().encode(stable(value))))}
async function add(type,payload){const all=await history(),prev=all.at(-1)?.hash||'GENESIS';const body={schema:'aksi-proof-v2',seq:all.length,type:String(type),payload:payload??{},previous_hash:prev,created_at:new Date().toISOString()};const hash=await digest(body);const s=await identity();const signature=hex(await subtle().sign({name:'Ed25519'},s.private_key,new TextEncoder().encode(stable({body,hash}))));const record={...body,hash,signature,public_key:s.public_key};await write(record);render();return record}
async function verify(){const all=await history();let prev='GENESIS',errors=[];for(const r of all){const copy={schema:r.schema,seq:r.seq,type:r.type,payload:r.payload,previous_hash:r.previous_hash,created_at:r.created_at};if(r.previous_hash!==prev||r.hash!==await digest(copy))errors.push({seq:r.seq,reason:'hash-or-chain'});try{const pub=await subtle().importKey('jwk',r.public_key,{name:'Ed25519'},true,['verify']);const ok=await subtle().verify({name:'Ed25519'},pub,new Uint8Array((r.signature.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16))),new TextEncoder().encode(stable({body:copy,hash:r.hash})));if(!ok)errors.push({seq:r.seq,reason:'signature'})}catch(e){errors.push({seq:r.seq,reason:'signature-unavailable'})}prev=r.hash}const status={ok:errors.length===0,length:all.length,errors};const s=document.getElementById('proofStatus');if(s)s.textContent=(status.ok?'✓ CRYPTOGRAPHIC CHAIN INTACT · ':'✕ VERIFICATION FAILED · ')+all.length+' RECORDS';return status}
function exportLog(){history().then(all=>{const blob=new Blob([JSON.stringify(all,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aksi-proof-ledger-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){const root=document.getElementById('proofRows');if(!root)return;history().then(all=>{root.innerHTML=all.slice(-8).reverse().map(r=>`<div class="proof-row"><b>${esc(r.type)}</b><span>${esc(r.created_at)}</span><code>${esc(r.hash.slice(0,24))}…</code></div>`).join('')||'<div class="proof-empty">Журнал пуст.</div>'})}
function mount(){if(document.querySelector('[data-proof-root]'))return;const host=document.querySelector('[data-view="trust"]')||document.querySelector('[data-view="home"]');if(!host)return;const box=document.createElement('section');box.dataset.proofRoot='1';box.className='proof-ledger';box.innerHTML='<div class="eyebrow">AKSI CRYPTOGRAPHIC PROOF</div><h2>Проверяемость, а не обещания</h2><p>Каждая запись получает SHA-256 digest, ссылку на предыдущую запись и Ed25519 signature. Ключи и журнал остаются локально в браузере.</p><div class="proof-actions"><button id="proofTest">Создать тестовую запись</button><button id="proofVerify">Проверить подписи</button><button id="proofExport">Экспортировать</button></div><div id="proofStatus" class="proof-status">LEDGER READY · GENESIS</div><div id="proofRows"></div>';host.appendChild(box);box.querySelector('#proofTest').onclick=()=>add('TEST',{message:'AKSI integrity test'}).catch(e=>box.querySelector('#proofStatus').textContent='ERROR · '+e.message);box.querySelector('#proofVerify').onclick=()=>verify().catch(e=>box.querySelector('#proofStatus').textContent='ERROR · '+e.message);box.querySelector('#proofExport').onclick=exportLog;render()}
window.AKSIProof={add,verify,history,digest,identity,stable,version:'2.0.0'};document.addEventListener('DOMContentLoaded',mount);
})();
