(function(){"use strict";
var S={entropy:null,bits:null,eqs:null,lastGate:null,did:null,chain:[],T:1.2,mag:null,Cv:null,phase:"—",Tc:2,spins:null,N:16,H_eff:null,energy:null},bus={},_booted=0;
function on(e,f){(bus[e]||(bus[e]=[])).push(f)}
function emit(e,d){S.chain.push({t:Date.now(),ev:e,d:d||0});if(S.chain.length>40)S.chain=S.chain.slice(-40);(bus[e]||[]).forEach(function(f){try{f(d)}catch(x){}});paintTop();paintChain()}
function $(i){return document.getElementById(i)}
function set(i,t){var e=$(i);if(e)e.textContent=t}
function mskNow(){try{return new Date().toLocaleTimeString("ru-RU",{timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})+" МСК"}catch(e){var x=new Date(Date.now()+108e5);function p(n){return(n<10?"0":"")+n}return p(x.getUTCHours())+":"+p(x.getUTCMinutes())+":"+p(x.getUTCSeconds())+" МСК"}}
function paintTop(){set("msk",mskNow());set("qEnt","H="+(S.entropy==null?"—":(+S.entropy).toFixed(2)));set("eqsLive","EQS="+(S.eqs==null?"—":S.eqs));set("gateLive","gate="+(S.lastGate||"—"));set("phaseLive","φ="+(S.phase||"—"));var b=$("sharedBox");if(b)b.textContent="T="+S.T.toFixed(2)+" · φ="+S.phase+" · m="+(S.mag==null?"—":(+S.mag).toFixed(3))+" · EQS="+(S.eqs==null?"—":S.eqs)+" · gate="+(S.lastGate||"—")}
function paintChain(){var el=$("chainLog");if(!el)return;el.textContent=S.chain.slice(-12).map(function(c){return c.ev+(c.d&&c.d.note?" · "+c.d.note:"")}).join("\n")||"пусто"}
function go(n){document.querySelectorAll(".panel").forEach(function(p){p.classList.toggle("on",p.getAttribute("data-p")===n)});document.querySelectorAll(".bnav button").forEach(function(b){b.classList.toggle("on",b.getAttribute("data-go")===n)});try{history.replaceState(null,"","#"+n)}catch(e){}window.scrollTo(0,0);if(n==="world")requestAnimationFrame(worldFrame);if(n==="phase")try{drawPhaseChart()}catch(e){}}
function b64(u){var s="",i;for(i=0;i<u.length;i++)s+=String.fromCharCode(u[i]);return btoa(s)}
async function ensureDid(){if(S.did&&S._priv)return;try{var kp=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);S._priv=kp.privateKey;var raw=new Uint8Array(await crypto.subtle.exportKey("raw",kp.publicKey));S.did="did:aksi:p256:"+b64(raw).replace(/[^a-zA-Z0-9]/g,"").slice(0,22)}catch(e){S.did="did:aksi:local"}set("didShort",(S.did||"").slice(0,16)+"…");set("didFull",S.did||"—")}
async function signPayload(o){await ensureDid();if(!S._priv)return"unsigned";try{var m=new TextEncoder().encode(JSON.stringify(o));return b64(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},S._priv,m)))}catch(e){return"err"}}
var J=1;
function textToSpins(t,N){N=N||16;var b=new TextEncoder().encode(String(t||"aksi"));if(!b.length)b=new Uint8Array([1]);var s=new Int8Array(N);for(var i=0;i<N;i++)s[i]=((b[i%b.length]>>(i%8))&1)?1:-1;return s}
function isingE(s){var E=0,n=s.length,i;for(i=0;i<n;i++)E-=J*s[i]*s[(i+1)%n];return E}
function mag(s){var x=0,i;for(i=0;i<s.length;i++)x+=s[i];return x/s.length}
function sweep(s,T){var n=s.length,beta=1/Math.max(T,1e-6),step,i,L,R,dE;for(step=0;step<n;step++){i=(Math.random()*n)|0;L=s[(i-1+n)%n];R=s[(i+1)%n];dE=2*J*s[i]*(L+R);if(dE<=0||Math.random()<Math.exp(-beta*dE))s[i]=-s[i]}return s}
function runGibbs(s0,T,sw){sw=sw||60;var s=new Int8Array(s0),burn=(sw/3)|0,sumM=0,sumE=0,sumE2=0,c=0,i,m,E;for(i=0;i<sw;i++){sweep(s,T);if(i>=burn){m=Math.abs(mag(s));E=isingE(s);sumM+=m;sumE+=E;sumE2+=E*E;c++}}c=c||1;var mE=sumE/c,vE=Math.max(0,sumE2/c-mE*mE);return{spins:s,mag:sumM/c,energy:mE,Cv:vE/(T*T)}}
function classPh(m,Cv,T,Tc){var near=Math.abs(T-Tc)/Tc<0.35;if(m>0.55&&T<Tc*1.1)return"ORDERED";if(m<0.25&&T>Tc*0.9)return"DISORDERED";if(near||(Cv>0.15&&m>0.2&&m<0.6))return"CRITICAL";return m>=0.4?"ORDERED":"DISORDERED"}
function phaseDiagram(text){var base=textToSpins(text,S.N),pts=[],k,T,r;for(k=0;k<=12;k++){T=0.3+3.2*(k/12);r=runGibbs(base,T,40);pts.push({T:T,m:r.mag})}return pts}
function applyPhase(text,T){T=T==null?S.T:T;S.T=T;S.Tc=2;var r=runGibbs(textToSpins(text,S.N),T,80);S.spins=r.spins;S.mag=r.mag;S.energy=r.energy;S.Cv=r.Cv;S.phase=classPh(r.mag,r.Cv,T,S.Tc);var up=0,i;for(i=0;i<r.spins.length;i++)if(r.spins[i]>0)up++;var p=up/r.spins.length,Ss=0;if(p>1e-9&&p<1-1e-9)Ss=-p*Math.log2(p)-(1-p)*Math.log2(1-p);S.H_eff=r.energy-T*Ss*r.spins.length*0.15;paintPhase();emit("phase",{note:S.phase+" m="+r.mag.toFixed(3)});return r}
function paintPhase(){set("phT",S.T.toFixed(3));set("phM",S.mag==null?"—":(+S.mag).toFixed(4));set("phE",S.energy==null?"—":(+S.energy).toFixed(4));set("phCv",S.Cv==null?"—":(+S.Cv).toFixed(4));set("phTc",S.Tc.toFixed(3));set("phPhase",S.phase);set("phHeff",S.H_eff==null?"—":(+S.H_eff).toFixed(4));var badge=$("phBadge");if(badge){badge.textContent=S.phase;badge.className="pill "+(S.phase==="ORDERED"?"ok":S.phase==="CRITICAL"?"warn":"bad")}var strip=$("spinStrip");if(strip&&S.spins){strip.innerHTML="";for(var i=0;i<S.spins.length;i++){var d=document.createElement("i");d.style.background=S.spins[i]>0?"#22d3ee":"#e879f9";strip.appendChild(d)}}try{drawPhaseChart()}catch(e){}}
var _dc=null;
function drawPhaseChart(){var c=$("phaseChart");if(!c||!c.getContext)return;var ctx=c.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth||320,h=140;c.width=(w*dpr)|0;c.height=(h*dpr)|0;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#0a0f1c";ctx.fillRect(0,0,w,h);var text=($("phaseIn")&&$("phaseIn").value)||"aksi";if(!_dc||_dc.t!==text)_dc={t:text,pts:phaseDiagram(text)};var pts=_dc.pts,Tmin=pts[0].T,Tmax=pts[pts.length-1].T;function xT(T){return 20+(w-36)*((T-Tmin)/(Tmax-Tmin||1))}function yM(m){return h-16-(h-28)*Math.min(1,Math.max(0,m))}ctx.strokeStyle="rgba(251,191,36,.5)";ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(xT(S.Tc),8);ctx.lineTo(xT(S.Tc),h-8);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle="#22d3ee";ctx.lineWidth=2;ctx.beginPath();pts.forEach(function(p,i){var x=xT(p.T),y=yM(p.m);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#fbbf24";ctx.beginPath();ctx.arc(xT(S.T),yM(S.mag||0),4,0,6.28);ctx.fill()}
var Q={n:4,dim:16,state:null};
function qInit(){Q.state=new Float64Array(32);Q.state[0]=1;paintQ();emit("quantum",{note:"|0>")}
function qNorm(){var s=0,i;for(i=0;i<16;i++)s+=Q.state[2*i]*Q.state[2*i]+Q.state[2*i+1]*Q.state[2*i+1];s=Math.sqrt(s)||1;for(i=0;i<32;i++)Q.state[i]/=s}
function applyH(q){var bit=1<<(3-q),next=new Float64Array(Q.state),s2=Math.SQRT1_2,i,i0,i1;for(i=0;i<16;i++){if(i&bit)continue;i0=i;i1=i|bit;var a0=Q.state[2*i0],b0=Q.state[2*i0+1],a1=Q.state[2*i1],b1=Q.state[2*i1+1];next[2*i0]=s2*(a0+a1);next[2*i0+1]=s2*(b0+b1);next[2*i1]=s2*(a0-a1);next[2*i1+1]=s2*(b0-b1)}Q.state=next;qNorm()}
function qAllH(){for(var q=0;q<4;q++)applyH(q);paintQ()}
function cnot(c,t){var cb=1<<(3-c),tb=1<<(3-t),next=new Float64Array(32),i,k;for(i=0;i<16;i++){if(i&cb){k=i^tb;next[2*k]=Q.state[2*i];next[2*k+1]=Q.state[2*i+1]}else{next[2*i]=Q.state[2*i];next[2*i+1]=Q.state[2*i+1]}}Q.state=next;qNorm()}
function qBell(){qInit();applyH(0);cnot(0,1);cnot(0,2);cnot(0,3);paintQ();emit("quantum",{note:"Bell"})}
function vonN(){if(!Q.state)qInit();var probs=[],H=0,i,p;for(i=0;i<16;i++){p=Q.state[2*i]*Q.state[2*i]+Q.state[2*i+1]*Q.state[2*i+1];probs.push(p);if(p>1e-14)H-=p*Math.log2(p)}return{H:H,probs:probs}}
function qCollapse(){var v=vonN(),r=Math.random(),acc=0,idx=0,i,bits;for(i=0;i<16;i++){acc+=v.probs[i];if(r<=acc){idx=i;break}}Q.state=new Float64Array(32);Q.state[2*idx]=1;bits=idx.toString(2);while(bits.length<4)bits="0"+bits;S.entropy=v.H;S.bits=bits;paintQ();emit("quantum-collapse",{note:bits});return{bits:bits,H:v.H}}
function paintQ(){var v=vonN();S.entropy=v.H;set("qHval",v.H.toFixed(4));set("qBits",S.bits||"—");set("qPur",S.bits?"1":"—");var bars=$("qBars");if(!bars)return;bars.innerHTML="";var maxp=Math.max.apply(null,v.probs.concat([1e-9])),i,el;for(i=0;i<16;i++){el=document.createElement("i");el.style.height=Math.max(2,(v.probs[i]/maxp)*90)+"%";bars.appendChild(el)}paintTop()}
function computeEQS(text){text=String(text||"");var coh=S.phase==="ORDERED"?0.9:S.phase==="CRITICAL"?0.55:0.35;if(S.mag!=null)coh=0.4*coh+0.6*Math.min(1,Math.abs(S.mag));var res=S.entropy==null?0.5:Math.max(0.2,1-S.entropy/4);var con=/[а-яА-Яa-zA-Z]{3,}/.test(text)?0.7:0.4;var integ=S.bits?0.75:0.45;var eqs=Math.round(100*(0.3*coh+0.25*res+0.25*con+0.2*integ));eqs=Math.max(0,Math.min(100,eqs));S.eqs=eqs;set("eqsVal",""+eqs);set("eqsVerdict",eqs>=70?"ALLOW-ready":eqs>=45?"REVIEW":"WEAK");set("eqsAxes",JSON.stringify({coh:coh,res:res,phase:S.phase}));emit("eqs",{note:"EQS="+eqs});paintTop();return eqs}
function simpleMath(text){var t=String(text).replace(/\s/g,"").replace(/,/g,".");var m=t.match(/^(\d+(?:\.\d+)?)([+\-*/×x])(\d+(?:\.\d+)?)$/);if(!m)return null;var a=+m[1],b=+m[3],op=m[2];if(op==="+")return a+b;if(op==="-")return a-b;if(op==="*"||op==="×"||op==="x")return a*b;if(op==="/"&&b)return a/b;return null}
function chatRespond(q){q=String(q||"").trim();if(!q)return"Напиши вопрос.";var math=simpleMath(q);if(math!=null)return"Результат: "+math+".";try{applyPhase(q,S.T)}catch(e){}if(S.entropy==null){try{qBell();qCollapse()}catch(e){}}var eqs=computeEQS(q);var low=q.toLowerCase();
if(/кто ты|что ты/.test(low))return"Я АКСИ Unity: чат + поле Гиббса + квант 4 кубита + EQS/gate. Offline в браузере.\nφ="+S.phase+" EQS="+eqs;
if(/привет|здравств|hello/.test(low))return"Привет. Сейчас "+mskNow()+". Спроси про фазу, квант или 12*12.";
if(/время|мск|москва|час/.test(low))return"Сейчас "+mskNow()+".";
if(/gibbs|гиббс|изинг|фаза|термо/.test(low))return"Гиббс: π∝e^{−βH}. Изинг-кольцо, Metropolis, |m|, Cv, фазы ORDERED/CRITICAL/DISORDERED. Сейчас φ="+S.phase+", |m|="+(S.mag==null?"—":(+S.mag).toFixed(3))+", T="+S.T.toFixed(2);
if(/квант|кубит|bell|коллапс/.test(low))return"Квант: 4 кубита, Bell, коллапс. H="+(S.entropy==null?"—":(+S.entropy).toFixed(3))+", bits="+(S.bits||"—");
if(/eqs|gate|allow|block/.test(low))return"EQS="+eqs+". Gate: ≥70 и не DISORDERED → ALLOW; иначе REVIEW/BLOCK.";
if(/помощ|help|умеешь/.test(low))return"Чат, Фаза (T, m(T)), Квант, Gate, «Связать всё» на Доме.";
return"По «"+q.slice(0,100)+"»: φ="+S.phase+", T="+S.T.toFixed(2)+", |m|="+(S.mag==null?"—":(+S.mag).toFixed(3))+", H="+(S.entropy==null?"—":(+S.entropy).toFixed(3))+", EQS="+eqs+"."}
function appendChat(role,text){var box=$("chatLog");if(!box)return;var d=document.createElement("div");d.className="cmsg "+(role==="user"?"cu":"ca");d.textContent=(role==="user"?"Вы: ":"АКСИ: ")+text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function sendChat(){var inp=$("chatIn");if(!inp)return;var q=inp.value.trim();if(!q)return;inp.value="";appendChat("user",q);appendChat("aksi",chatRespond(q));emit("chat",{note:q.slice(0,30)})}
async function runGate(claim){claim=String(claim||"").trim();var tr=[];tr.push("[1] "+claim.slice(0,60));try{applyPhase(claim,S.T);tr.push("[2] φ="+S.phase)}catch(e){}try{if(S.entropy==null){qBell();qCollapse()}tr.push("[3] "+(S.bits||"—"))}catch(e){}var eqs=computeEQS(claim);tr.push("[4] EQS="+eqs);var math=simpleMath(claim);if(math!=null)tr.push("[math] "+math);var dec="REVIEW";if(eqs>=70&&S.phase!=="DISORDERED")dec="ALLOW";else if(eqs<45||S.phase==="DISORDERED")dec="BLOCK";if(math!=null&&eqs>=50)dec="ALLOW";S.lastGate=dec;var body={system:"AKSI-UNITY-v3",claim:claim,decision:dec,eqs:eqs,phase:S.phase,T:S.T,mag:S.mag,quantum:{H:S.entropy,bits:S.bits},did:S.did,ts:new Date().toISOString()};body.signature=await signPayload(body);set("trace",tr.join("\n"));var out=$("out");if(out){out.className="msg "+(dec==="ALLOW"?"allow":dec==="BLOCK"?"block":"");out.innerHTML="<span class=\"pill "+(dec==="ALLOW"?"ok":dec==="BLOCK"?"bad":"warn")+"\">"+dec+"</span> EQS "+eqs+" · φ "+S.phase+"<div class=\"meta\">"+JSON.stringify(body).slice(0,240)+"…</div>"}emit("gate",{note:dec});paintTop();W.gate=dec;try{localStorage.setItem("aksi_unity_last",JSON.stringify(body))}catch(e){}return body}
var W={pts:[],gate:null};
function worldInit(){W.pts=[];for(var i=0;i<40;i++)W.pts.push({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.004,vy:(Math.random()-.5)*.004})}
function worldFrame(){var c=$("worldC");if(!c||!c.getContext)return;var ctx=c.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth||360,h=220;c.width=(w*dpr)|0;c.height=(h*dpr)|0;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#05010f";ctx.fillRect(0,0,w,h);var sp=1+(S.entropy||0)*.4;if(S.phase==="CRITICAL")sp*=1.5;var col=W.gate==="ALLOW"?"#34d399":W.gate==="BLOCK"?"#f87171":"#818cf8";W.pts.forEach(function(p){p.x+=p.vx*sp;p.y+=p.vy*sp;if(p.x<0||p.x>1)p.vx*=-1;if(p.y<0||p.y>1)p.vy*=-1;ctx.beginPath();ctx.fillStyle=col;ctx.globalAlpha=.75;ctx.arc(p.x*w,p.y*h,2.5,0,6.28);ctx.fill()});ctx.globalAlpha=1;if(document.querySelector('.panel.on[data-p="world"]'))requestAnimationFrame(worldFrame)}
async function linkAll(){var claim=($("claim")&&$("claim").value)||($("phaseIn")&&$("phaseIn").value)||"АКСИ";emit("pipeline",{note:"start"});applyPhase(claim,S.T);qBell();qCollapse();computeEQS(claim);await runGate(claim);emit("pipeline",{note:"done "+S.lastGate});go("home")}
function boot(){if(_booted)return;_booted=1;
document.querySelectorAll(".bnav button").forEach(function(b){b.addEventListener("click",function(){go(b.getAttribute("data-go"))})});
document.querySelectorAll("[data-jump]").forEach(function(b){b.addEventListener("click",function(){go(b.getAttribute("data-jump"))})});
var h=(location.hash||"").replace("#","");if(h)go(h);ensureDid();qInit();worldInit();
if($("btnLinkAll"))$("btnLinkAll").onclick=function(){linkAll()};
var ts=$("tempSlider");if(ts)ts.oninput=function(){S.T=parseFloat(ts.value)||1.2;set("phT",S.T.toFixed(3))};
if($("btnPhase"))$("btnPhase").onclick=function(){_dc=null;applyPhase(($("phaseIn")&&$("phaseIn").value)||"aksi",S.T)};
if($("btnScan"))$("btnScan").onclick=function(){_dc=null;drawPhaseChart()};
if($("qInit"))$("qInit").onclick=qInit;if($("qH"))$("qH").onclick=qAllH;if($("qEntangle"))$("qEntangle").onclick=qBell;if($("qCollapse"))$("qCollapse").onclick=qCollapse;
if($("wPulse"))$("wPulse").onclick=function(){go("world");worldFrame()};if($("wReset"))$("wReset").onclick=worldInit;
if($("algoRun"))$("algoRun").onclick=function(){computeEQS(($("algoIn")&&$("algoIn").value)||"")};
if($("btnRun"))$("btnRun").onclick=function(){runGate(($("claim")&&$("claim").value)||"")};
if($("btnClear"))$("btnClear").onclick=function(){if($("claim"))$("claim").value="";set("trace","…");if($("out")){$("out").className="msg";$("out").textContent="нет receipt"}};
if($("btnRotate"))$("btnRotate").onclick=function(){S.did=null;S._priv=null;ensureDid()};
if($("btnVerify"))$("btnVerify").onclick=function(){try{var o=JSON.parse(($("verifyBox")&&$("verifyBox").value)||"{}");set("verifyOut",o.decision?"OK "+o.decision:"нет decision")}catch(e){set("verifyOut","JSON error")}};
if($("btnChat"))$("btnChat").onclick=sendChat;
if($("chatIn"))$("chatIn").addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendChat()}});
applyPhase("АКСИ",S.T);appendChat("aksi","Онлайн. "+mskNow()+". Спроси что угодно.");
setInterval(paintTop,1000);paintTop()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
window.AKSIUnity={applyPhase:applyPhase,chatRespond:chatRespond,runGate:runGate,linkAll:linkAll,state:function(){return S}};
})();
