/** AKSI Runtime Contract v1.3 — one public orchestration boundary. */
(function(g){'use strict';
var V='1.3.0',providers={core:['AKSI_CORE','query'],local:['AKSI_LOCAL_ENGINE','ask'],metrics:['AKSI_METRICS','measure'],proof:['AKSIProof','add'],llm:['AKSI_LLM','complete']};
function inspect(n){var s=providers[n],x=g[s[0]];return {name:n,global:s[0],available:!!x,ready:!!x&&typeof x[s[1]]==='function'};}
function status(){var p={};Object.keys(providers).forEach(function(n){p[n]=inspect(n)});return {schema:'AKSI-RUNTIME-1',version:V,runtime:p.local.ready||p.core.ready?'ready':'degraded',timestamp:Date.now(),providers:p,integrity:{crypto:!!(g.crypto&&g.crypto.subtle)}};}
function canonical(v){if(v===undefined)return'null';if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).filter(function(k){return v[k]!==undefined&&typeof v[k]!=='function';}).sort().map(function(k){return JSON.stringify(k)+':'+canonical(v[k]);}).join(',')+'}';}
function answer(input,text,meta){meta=meta||{};return{schema:'AKSI-ANSWER-1',input:String(input||''),text:String(text||''),source:String(meta.source||'unknown'),kind:String(meta.kind||'unverified'),confidence:typeof meta.confidence==='number'?Math.max(0,Math.min(1,meta.confidence)):null,citations:Array.isArray(meta.citations)?meta.citations.slice(0,20):[],generatedAt:Date.now()};}
async function sha256(v){if(!g.crypto||!g.crypto.subtle)throw Error('WebCrypto unavailable');var b=new TextEncoder().encode(canonical(v)),d=await g.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(d)).map(function(x){return x.toString(16).padStart(2,'0')}).join('');}
async function execute(input,opts){opts=opts||{};var q=String(input||'').trim();if(!q)throw Error('Empty input');var started=performance.now(),events=[];function ev(type,data){events.push({type:type,data:data||{},at:Date.now()});}
ev('input.received',{chars:q.length});var result;
if(g.AKSI_LOCAL_ENGINE&&typeof g.AKSI_LOCAL_ENGINE.ask==='function'){ev('route.local');result=await g.AKSI_LOCAL_ENGINE.ask(q,{useMemory:opts.useMemory!==false,allowLocalServer:opts.allowLocalServer===true});}
else if(g.AKSI_CORE&&typeof g.AKSI_CORE.query==='function'){ev('route.core');result=await g.AKSI_CORE.query(q,{allowNetwork:opts.allowNetwork===true});}
else throw Error('No AKSI provider available');
ev('answer.received',{source:result.source||'unknown',chars:String(result.text||'').length});var a=answer(q,result.text,{source:result.source||'unknown',kind:result.offline?'local':'unverified',citations:result.sources||[]});a.metrics= g.AKSI_METRICS&&typeof g.AKSI_METRICS.measure==='function'?g.AKSI_METRICS.measure({input:q,output:a.text,source:a.source,trace:events}):null;a.trace=events;a.latencyMs=Math.round(performance.now()-started);a.integrityHash=await sha256(a);ev('verification.complete',{hash:a.integrityHash,latencyMs:a.latencyMs});return a;}
async function selfTest(){var s=status(),proof=false;try{proof=(await sha256({test:'AKSI'})).length===64;}catch(e){}return{ok:s.runtime==='ready'&&s.integrity.crypto,version:V,status:s,sha256:proof};}
g.AKSI_RUNTIME={version:V,status:status,answer:answer,canonical:canonical,sha256:sha256,execute:execute,selfTest:selfTest};
})(typeof window!=='undefined'?window:this);