/**
 * AKSI Core v6.0
 * Public, privacy-safe orchestration layer.
 * Network access is explicit; no credentials or personal data are embedded.
 */
(function(G){'use strict';
var VERSION='6.0.0',CACHE='aksi_core_cache_v2',TTL=18e5;
function hash(s){var h=0x811c9dc5,i;for(i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,0x01000193)}return('00000000'+(h>>>0).toString(16)).slice(-8)}
function cacheGet(q){try{var c=JSON.parse(localStorage.getItem(CACHE)||'{}'),e=c[hash(q)];return e&&Date.now()-e.ts<TTL?e.data:null}catch(e){return null}}
function cacheSet(q,d){try{var c=JSON.parse(localStorage.getItem(CACHE)||'{}');c[hash(q)]={ts:Date.now(),data:d};localStorage.setItem(CACHE,JSON.stringify(c))}catch(e){}}
function fetchJson(url,ms){ms=ms||5500;return new Promise(function(resolve,reject){var done=false,ctrl=typeof AbortController!=='undefined'?new AbortController():null,t=setTimeout(function(){if(done)return;done=true;if(ctrl)try{ctrl.abort()}catch(e){}reject(new Error('timeout'))},ms);fetch(url,{headers:{Accept:'application/json'},signal:ctrl&&ctrl.signal}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(function(j){if(done)return;done=true;clearTimeout(t);resolve(j)}).catch(function(e){if(done)return;done=true;clearTimeout(t);reject(e)})})}
function cleanQuery(q){return String(q||'').replace(/^(найди|поиск|search|wiki\s*:)\s*/i,'').replace(/^(что такое|кто такой|кто такая|расскажи про|расскажи о|объясни)\s+/i,'').replace(/\?+$/g,'').trim()||String(q||'').trim()}
function localKnowledge(q){var x=String(q||'').toLowerCase().trim();if(!x)return null;if(/^(привет|здравств|добрый|hello|hi|hey)\b/.test(x))return'Готова к работе. Локальный режим активен.';if(/^(пока|до связи|bye)\b/.test(x))return'До связи. Локальные данные остаются на устройстве.';if(/спасибо|благодар/.test(x))return'Пожалуйста.';if(/кто ты|что ты такое|who are you/.test(x))return'Ядро AKSI v'+VERSION+'. Local-first orchestration, memory, retrieval и verification.';if(/что умеешь|что можешь|помощь|help|команды/.test(x))return'Local AI · Memory · Retrieval · Metrics · Proof · Tools · MATRIX.';if(/формул|aksi\s*=/.test(x))return'AKSI Index = (A × I × S) × (1 + γ√n). γ — настраиваемый коэффициент, а не физическая константа.';return null}
function wiki(q){var u='https://ru.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(q);return fetchJson(u).then(function(j){return j&&j.extract?[{source:'wikipedia',title:j.title||q,text:String(j.extract).slice(0,1400),url:j.content_urls&&j.content_urls.desktop&&j.content_urls.desktop.page||''}]:[]}).catch(function(){return[]})}
function ddg(q){var u='https://api.duckduckgo.com/?q='+encodeURIComponent(q)+'&format=json&no_html=1&skip_disambig=1';return fetchJson(u).then(function(j){var a=[];if(j&&j.AbstractText)a.push({source:'duckduckgo',title:j.Heading||q,text:String(j.AbstractText).slice(0,1100),url:j.AbstractURL||''});return a}).catch(function(){return[]})}
function compose(q,hits){if(!hits.length)return{ok:false,text:'Нет проверенного локального или сетевого результата. Уточни запрос.',sources:[],hits:[]};var h=hits[0],src=[];hits.forEach(function(x){if(x.url&&src.indexOf(x.url)<0)src.push(x.url)});return{ok:true,text:(h.title&&h.title!=='Ответ'?h.title+'\n\n':'')+String(h.text||'')+(src.length?'\n\nИсточники:\n'+src.slice(0,3).map(function(u,i){return(i+1)+'. '+u}).join('\n'):''),sources:src,hits:hits,source:h.source}}
function query(q,opts){opts=opts||{};q=String(q||'').trim();if(!q)return Promise.resolve({ok:false,text:'Пустой запрос',sources:[],hits:[]});var local=localKnowledge(q);if(local&&!opts.forceNet)return Promise.resolve({ok:true,text:local,local:true,sources:[],hits:[],offline:true});var sq=cleanQuery(q),cached=!opts.noCache&&cacheGet(sq);if(cached)return Promise.resolve(cached);if(opts.allowNetwork!==true)return Promise.resolve({ok:false,text:'Сеть отключена политикой local-first. Разреши network для этого запроса.',sources:[],hits:[],offline:true});return Promise.all([wiki(sq),ddg(sq)]).then(function(p){var h=(p[0]||[]).concat(p[1]||[]),r=compose(q,h);r.offline=false;cacheSet(sq,r);return r})}
function needsNet(q){var x=String(q||'').toLowerCase().trim();return !!(x.length>2&&!localKnowledge(x)&&(/\?$/.test(x)||/^(поиск|найди|что|кто|как|почему|где|когда|сколько|расскажи)/.test(x)))}
var api={version:VERSION,query:query,ask:query,needsNet:needsNet,cleanQuery:cleanQuery,localKnowledge:localKnowledge};G.AKSI_CORE=api;G.AksiCore=api;
})(typeof window!=='undefined'?window:this);
