(function(){"use strict";
var S={entropy:null,bits:null,eqs:null,lastGate:null,did:null,chain:[],T:1.2,mag:null,Cv:null,phase:"—",Tc:2,spins:null,N:16,H_eff:null,energy:null},bus={},_booted=0,W={pts:[],gate:null},Q={state:null},_dc=null,J=1;
function $(i){return document.getElementById(i)}
function set(i,t){var e=$(i);if(e)e.textContent=t}
function emit(e,d){S.chain.push({t:Date.now(),ev:e,d:d||0});if(S.chain.length>30)S.chain=S.chain.slice(-30);paintTop();var el=$("chainLog");if(el)el.textContent=S.chain.slice(-6).map(function(c){return c.ev}).join(" · ")||"—"}
function mskNow(){try{return new Date().toLocaleTimeString("ru-RU",{timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})+" МСК"}catch(e){var x=new Date(Date.now()+108e5);function p(n){return(n<10?"0":"")+n}return p(x.getUTCHours())+":"+p(x.getUTCMinutes())+":"+p(x.getUTCSeconds())+" МСК"}}
function paintTop(){set("msk",mskNow());set("qEnt","H="+(S.entropy==null?"—":(+S.entropy).toFixed(2)));set("eqsLive","EQS="+(S.eqs==null?"—":S.eqs));set("gateLive","gate="+(S.lastGate||"—"));set("phaseLive","φ="+(S.phase||"—"));var b=$("sharedBox");if(b)b.textContent="T="+S.T.toFixed(2)+" · φ="+S.phase+" · m="+(S.mag==null?"—":(+S.mag).toFixed(3))+" · EQS="+(S.eqs==null?"—":S.eqs)}
function go(n){document.querySelectorAll(".panel").forEach(function(p){p.classList.toggle("on",p.getAttribute("data-p")===n)});document.querySelectorAll(".bnav button").forEach(function(b){b.classList.toggle("on",b.getAttribute("data-go")===n)});try{history.replaceState(null,"","#"+n)}catch(e){}if(n==="world")requestAnimationFrame(worldFrame);if(n==="phase")try{drawPhaseChart()}catch(e){};if(n==="chat"){var inp=$("chatIn");if(inp)setTimeout(function(){inp.focus()},100)}}
function b64(u){var s="",i;for(i=0;i<u.length;i++)s+=String.fromCharCode(u[i]);return btoa(s)}
async function ensureDid(){if(S.did&&S._priv)return;try{var kp=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);S._priv=kp.privateKey;var raw=new Uint8Array(await crypto.subtle.exportKey("raw",kp.publicKey));S.did="did:aksi:p256:"+b64(raw).replace(/[^a-zA-Z0-9]/g,"").slice(0,20)}catch(e){S.did="did:aksi:local"}set("didShort",(S.did||"").slice(0,14)+"…");set("didFull",S.did||"—")}
async function signPayload(o){await ensureDid();if(!S._priv)return"unsigned";try{return b64(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},S._priv,new TextEncoder().encode(JSON.stringify(o)))))}catch(e){return"err"}}
function toks(s){s=String(s).toLowerCase().replace(/,/g,".").replace(/×/g,"*").replace(/÷/g,"/").replace(/−/g,"-");s=s.replace(/π/g," pi ").replace(/\bpi\b/g," pi ");s=s.replace(/√\s*\(/g,"sqrt(").replace(/√\s*(\d+(?:\.\d+)?)/g,"sqrt($1)");s=s.replace(/корень(?:\s*из)?\s*\(?\s*([\d.]+)\s*\)?/g,"sqrt($1)");var out=[],i=0,n=s.length;while(i<n){var c=s[i];if(c===" "||c==="\t"){i++;continue}if(/[0-9.]/.test(c)){var j=i;while(j<n&&/[0-9.]/.test(s[j]))j++;out.push({t:"n",v:parseFloat(s.slice(i,j))});i=j;continue}if(/[a-zа-я]/i.test(c)){var k=i;while(k<n&&/[a-zа-я0-9_]/i.test(s[k]))k++;var w=s.slice(i,k);if(w==="pi")out.push({t:"n",v:Math.PI});else if(w==="e")out.push({t:"n",v:Math.E});else out.push({t:"f",v:w});i=k;continue}if(c==="*"&&s[i+1]==="*"){out.push({t:"o",v:"**"});i+=2;continue}if(c==="^"){out.push({t:"o",v:"**"});i++;continue}if("+-*/()".indexOf(c)>=0){out.push({t:"o",v:c});i++;continue}i++}return out}
function toRPN(tokens){var prec={"**":4,"*":3,"/":3,"+":2,"-":2},right={"**":1},out=[],st=[],i,tk;for(i=0;i<tokens.length;i++){tk=tokens[i];if(tk.t==="n")out.push(tk);else if(tk.t==="f")st.push(tk);else if(tk.v==="(")st.push(tk);else if(tk.v===")"){while(st.length&&st[st.length-1].v!=="(")out.push(st.pop());if(st.length)st.pop();if(st.length&&st[st.length-1].t==="f")out.push(st.pop())}else if(tk.t==="o"){if(tk.v==="-"&&(i===0||(tokens[i-1].t==="o"&&tokens[i-1].v!==")")))out.push({t:"n",v:0});while(st.length&&st[st.length-1].t==="o"){var top=st[st.length-1].v,pr=prec[tk.v]||0,pt=prec[top]||0;if(right[tk.v]?pr<pt:pr<=pt)out.push(st.pop());else break}st.push(tk)}}while(st.length)out.push(st.pop());return out}
function evalRPN(rpn){var st=[],i,tk,a,b;for(i=0;i<rpn.length;i++){tk=rpn[i];if(tk.t==="n")st.push(tk.v);else if(tk.t==="f"){a=st.pop();if(a==null)throw 0;if(tk.v==="sqrt")st.push(Math.sqrt(a));else if(tk.v==="sin")st.push(Math.sin(a));else if(tk.v==="cos")st.push(Math.cos(a));else if(tk.v==="tan")st.push(Math.tan(a));else if(tk.v==="log")st.push(Math.log(a)/Math.LN10);else if(tk.v==="ln")st.push(Math.log(a));else if(tk.v==="abs")st.push(Math.abs(a));else throw 0}else{b=st.pop();a=st.pop();if(a==null||b==null)throw 0;if(tk.v==="+")st.push(a+b);else if(tk.v==="-")st.push(a-b);else if(tk.v==="*")st.push(a*b);else if(tk.v==="/"){if(!b)throw 0;st.push(a/b)}else if(tk.v==="**")st.push(Math.pow(a,b));else throw 0}}if(st.length!==1)throw 0;return st[0]}
function evalExpr(s){try{return evalRPN(toRPN(toks(s)))}catch(e){return null}}
function fmt(x){if(x==null||!isFinite(x))return"—";if(Math.abs(x-Math.round(x))<1e-10)return String(Math.round(x));return String(parseFloat(x.toFixed(10)))}
function solveQuad(a,b,c){if(Math.abs(a)<1e-12){if(Math.abs(b)<1e-12)return[];return[-c/b]}var d=b*b-4*a*c;if(d<-1e-12)return[];if(Math.abs(d)<1e-12)return[-b/(2*a)];var s=Math.sqrt(d);return[(-b+s)/(2*a),(-b-s)/(2*a)]}
function parseEq(q){var s=String(q).toLowerCase().replace(/,/g,".").replace(/\s/g,"").replace(/х/g,"x").replace(/\*/g,"");if(s.indexOf("=")<0)return null;var L=s.split("=")[0],R=s.split("=")[1],rN=parseFloat(R);if(!isFinite(rN)||/[x]/.test(R))return null;var a=0,b=0,c=0,e=L,m;m=e.match(/([+-]?\d*\.?\d*)x\^2/);if(m){a=m[1]===""||m[1]==="+"?1:m[1]==="-"?-1:parseFloat(m[1]);e=e.replace(m[0],"")}m=e.match(/([+-]?\d*\.?\d*)x/);if(m){b=m[1]===""||m[1]==="+"?1:m[1]==="-"?-1:parseFloat(m[1]);e=e.replace(m[0],"")}e.replace(/([+-]?\d+\.?\d*)/g,function(n){c+=parseFloat(n);return""});c-=rN;return{a:a,b:b,c:c}}
function mathAnswer(q){var raw=String(q).trim(),low=raw.toLowerCase();var pm=low.match(/(\d+(?:[.,]\d+)?)\s*%\s*(?:от)?\s*(\d+(?:[.,]\d+)?)/);if(pm)return pm[1]+"% от "+pm[2]+" = "+fmt((+pm[1].replace(",","."))/100*(+pm[2].replace(",",".")));var fm=low.match(/(\d+)\s*!/);if(fm){var n=+fm[1],f=1,i;if(n>20)return"n! слишком велико (n≤20)";for(i=2;i<=n;i++)f*=i;return n+"! = "+f}if(/=/.test(raw)&&/[xх]/i.test(raw)){var p=parseEq(raw);if(p){var rs=solveQuad(p.a,p.b,p.c);if(!rs.length)return"Уравнение: "+raw+"\nДействительных корней нет.";return"Уравнение: "+raw+"\nКорни: "+rs.map(fmt).join(", ")}}var expr=raw.replace(/^посчитай\s*/i,"").replace(/^вычисли\s*/i,"").replace(/^сколько\s+будет\s*/i,"");if(!/=/.test(expr)||!/[xх]/i.test(expr)){var v=evalExpr(expr);if(v!=null)return"Выражение: "+expr.trim()+"\nРезультат: "+fmt(v)}var gm=low.match(/(?:нод|gcd)\s*(\d+)\s*(?:и|,)?\s*(\d+)/);if(gm){function g(a,b){while(b){var t=b;b=a%b;a=t}return a}return"НОД("+gm[1]+", "+gm[2]+") = "+g(+gm[1],+gm[2])}var lm=low.match(/(?:нок|lcm)\s*(\d+)\s*(?:и|,)?\s*(\d+)/);if(lm){function g2(a,b){while(b){var t=b;b=a%b;a=t}return a}var A=+lm[1],B=+lm[2];return"НОК("+A+", "+B+") = "+(A*B/g2(A,B))}return null}
function textToSpins(t,N){N=N||16;var b=new TextEncoder().encode(String(t||"aksi"));if(!b.length)b=new Uint8Array([1]);var s=new Int8Array(N);for(var i=0;i<N;i++)s[i]=((b[i%b.length]>>(i%8))&1)?1:-1;return s}
function isingE(s){var E=0,n=s.length,i;for(i=0;i<n;i++)E-=J*s[i]*s[(i+1)%n];return E}
function mag(s){var x=0,i;for(i=0;i<s.length;i++)x+=s[i];return x/s.length}
function sweep(s,T){var n=s.length,beta=1/Math.max(T,1e-6),step,i,L,R,dE;for(step=0;step<n;step++){i=(Math.random()*n)|0;L=s[(i-1+n)%n];R=s[(i+1)%n];dE=2*J*s[i]*(L+R);if(dE<=0||Math.random()<Math.exp(-beta*dE))s[i]=-s[i]}return s}
function runGibbs(s0,T,sw){sw=sw||50;var s=new Int8Array(s0),burn=(sw/3)|0,sumM=0,sumE=0,sumE2=0,c=0,i,m,E;for(i=0;i<sw;i++){sweep(s,T);if(i>=burn){m=Math.abs(mag(s));E=isingE(s);sumM+=m;sumE+=E;sumE2+=E*E;c++}}c=c||1;var mE=sumE/c;return{spins:s,mag:sumM/c,energy:mE,Cv:Math.max(0,sumE2/c-mE*mE)/(T*T)}}
function classPh(m,Cv,T,Tc){if(m>0.55&&T<Tc*1.1)return"ORDERED";if(m<0.25&&T>Tc*0.9)return"DISORDERED";if(Math.abs(T-Tc)/Tc<0.35||(Cv>0.15&&m>0.2&&m<0.6))return"CRITICAL";return m>=0.4?"ORDERED":"DISORDERED"}
function applyPhase(text,T){T=T==null?S.T:T;S.T=T;S.Tc=2;var r=runGibbs(textToSpins(text,S.N),T,60);S.spins=r.spins;S.mag=r.mag;S.energy=r.energy;S.Cv=r.Cv;S.phase=classPh(r.mag,r.Cv,T,S.Tc);S.H_eff=r.energy;paintPhase();return r}
function paintPhase(){set("phT",S.T.toFixed(3));set("phM",S.mag==null?"—":(+S.mag).toFixed(4));set("phE",S.energy==null?"—":(+S.energy).toFixed(4));set("phCv",S.Cv==null?"—":(+S.Cv).toFixed(4));set("phTc",S.Tc.toFixed(3));set("phPhase",S.phase);set("phHeff",S.H_eff==null?"—":(+S.H_eff).toFixed(4));var badge=$("phBadge");if(badge){badge.textContent=S.phase;badge.className="pill "+(S.phase==="ORDERED"?"ok":S.phase==="CRITICAL"?"warn":"bad")}var strip=$("spinStrip");if(strip&&S.spins){strip.innerHTML="";for(var i=0;i<S.spins.length;i++){var d=document.createElement("i");d.style.background=S.spins[i]>0?"#22d3ee":"#e879f9";strip.appendChild(d)}}try{drawPhaseChart()}catch(e){}}
function phaseDiagram(text){var base=textToSpins(text,S.N),pts=[],k,T,r;for(k=0;k<=10;k++){T=0.3+3.2*(k/10);r=runGibbs(base,T,30);pts.push({T:T,m:r.mag})}return pts}
function drawPhaseChart(){var c=$("phaseChart");if(!c||!c.getContext)return;var ctx=c.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth||320,h=140;c.width=(w*dpr)|0;c.height=(h*dpr)|0;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#0a0f1c";ctx.fillRect(0,0,w,h);var text=($("phaseIn")&&$("phaseIn").value)||"aksi";if(!_dc||_dc.t!==text)_dc={t:text,pts:phaseDiagram(text)};var pts=_dc.pts,Tmin=pts[0].T,Tmax=pts[pts.length-1].T;function xT(T){return 20+(w-36)*((T-Tmin)/(Tmax-Tmin||1))}function yM(m){return h-16-(h-28)*Math.min(1,Math.max(0,m))}ctx.strokeStyle="rgba(251,191,36,.5)";ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(xT(S.Tc),8);ctx.lineTo(xT(S.Tc),h-8);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle="#22d3ee";ctx.lineWidth=2;ctx.beginPath();pts.forEach(function(p,i){var x=xT(p.T),y=yM(p.m);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#fbbf24";ctx.beginPath();ctx.arc(xT(S.T),yM(S.mag||0),4,0,6.28);ctx.fill()}
function qInit(){Q.state=new Float64Array(32);Q.state[0]=1;paintQ()}
function qNorm(){var s=0,i;for(i=0;i<16;i++)s+=Q.state[2*i]*Q.state[2*i]+Q.state[2*i+1]*Q.state[2*i+1];s=Math.sqrt(s)||1;for(i=0;i<32;i++)Q.state[i]/=s}
function applyH(q){var bit=1<<(3-q),next=new Float64Array(Q.state),s2=Math.SQRT1_2,i,i0,i1;for(i=0;i<16;i++){if(i&bit)continue;i0=i;i1=i|bit;var a0=Q.state[2*i0],b0=Q.state[2*i0+1],a1=Q.state[2*i1],b1=Q.state[2*i1+1];next[2*i0]=s2*(a0+a1);next[2*i0+1]=s2*(b0+b1);next[2*i1]=s2*(a0-a1);next[2*i1+1]=s2*(b0-b1)}Q.state=next;qNorm()}
function qAllH(){for(var q=0;q<4;q++)applyH(q);paintQ()}
function cnot(c,t){var cb=1<<(3-c),tb=1<<(3-t),next=new Float64Array(32),i,k;for(i=0;i<16;i++){if(i&cb){k=i^tb;next[2*k]=Q.state[2*i];next[2*k+1]=Q.state[2*i+1]}else{next[2*i]=Q.state[2*i];next[2*i+1]=Q.state[2*i+1]}}Q.state=next;qNorm()}
function qBell(){qInit();applyH(0);cnot(0,1);cnot(0,2);cnot(0,3);paintQ()}
function vonN(){if(!Q.state)qInit();var probs=[],H=0,i,p;for(i=0;i<16;i++){p=Q.state[2*i]*Q.state[2*i]+Q.state[2*i+1]*Q.state[2*i+1];probs.push(p);if(p>1e-14)H-=p*Math.log2(p)}return{H:H,probs:probs}}
function qCollapse(){var v=vonN(),r=Math.random(),acc=0,idx=0,i,bits;for(i=0;i<16;i++){acc+=v.probs[i];if(r<=acc){idx=i;break}}Q.state=new Float64Array(32);Q.state[2*idx]=1;bits=idx.toString(2);while(bits.length<4)bits="0"+bits;S.entropy=v.H;S.bits=bits;paintQ();return{bits:bits,H:v.H}}
function paintQ(){var v=vonN();S.entropy=v.H;set("qHval",v.H.toFixed(4));set("qBits",S.bits||"—");set("qPur",S.bits?"1":"—");var bars=$("qBars");if(!bars)return;bars.innerHTML="";var maxp=Math.max.apply(null,v.probs.concat([1e-9])),i,el;for(i=0;i<16;i++){el=document.createElement("i");el.style.height=Math.max(2,(v.probs[i]/maxp)*90)+"%";bars.appendChild(el)}paintTop()}
function computeEQS(text){text=String(text||"");var coh=S.phase==="ORDERED"?0.9:S.phase==="CRITICAL"?0.55:0.35;if(S.mag!=null)coh=0.4*coh+0.6*Math.min(1,Math.abs(S.mag));var res=S.entropy==null?0.5:Math.max(0.2,1-S.entropy/4);var con=/[а-яА-Яa-zA-Z]{3,}/.test(text)?0.7:0.4;var integ=S.bits?0.75:0.45;var eqs=Math.round(100*(0.3*coh+0.25*res+0.25*con+0.2*integ));S.eqs=Math.max(0,Math.min(100,eqs));set("eqsVal",""+S.eqs);set("eqsVerdict",S.eqs>=70?"ALLOW-ready":S.eqs>=45?"REVIEW":"WEAK");set("eqsAxes","φ="+S.phase);paintTop();return S.eqs}
function chatRespond(q){q=String(q||"").trim();if(!q)return"Напиши выражение или уравнение.";var m=mathAnswer(q);if(m){try{applyPhase(q,S.T);if(S.entropy==null){qBell();qCollapse()}computeEQS(q)}catch(e){}return m}var low=q.toLowerCase();if(/кто ты|что ты/.test(low))return"АКСИ Unity — offline math: RPN-парсер, уравнения, %, n!, НОД. Гиббс + 4-кубитный симулятор.";if(/привет|здравств|hello/.test(low))return"Привет. 2+2*3 · sqrt(2) · x^2-4=0 · 15% от 80 · 5!";if(/время|мск|час/.test(low))return mskNow();if(/gibbs|гиббс|фаза|термо|изинг/.test(low)){try{applyPhase(q,S.T)}catch(e){}return"Гиббс π∝e^{−βH}. φ="+S.phase+", T="+S.T.toFixed(2)+", |m|="+(S.mag==null?"—":(+S.mag).toFixed(4))}if(/квант|кубит|bell|коллапс/.test(low)){try{if(S.entropy==null){qBell();qCollapse()}}catch(e){}return"H="+(S.entropy==null?"—":(+S.entropy).toFixed(4))+", bits="+(S.bits||"—")}if(/помощ|help|умеешь/.test(low))return"2+2*3 · (3+4)^2 · sqrt(16) · pi*2 · x^2-5x+6=0 · 20% от 150 · 6! · нод 24 36";var em=q.match(/([\d(][\d+\-*/().\s^√πpie×÷]*[\d)πe])/i);if(em){var vv=evalExpr(em[1]);if(vv!=null)return"«"+em[1].trim()+"» → "+fmt(vv)}try{applyPhase(q,S.T);if(S.entropy==null){qBell();qCollapse()}computeEQS(q)}catch(e){}return"Не выражение. Примеры: 17*19 · x^2=9 · корень из 49.\nφ="+S.phase+" EQS="+S.eqs}
function appendChat(role,text){var box=$("chatLog");if(!box)return;var d=document.createElement("div");d.className="cmsg "+(role==="user"?"cu":"ca");d.textContent=(role==="user"?"Вы: ":"АКСИ: ")+text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function sendChat(){var inp=$("chatIn");if(!inp)return;var q=inp.value.trim();if(!q)return;inp.value="";appendChat("user",q);appendChat("aksi",chatRespond(q))}
async function runGate(claim){claim=String(claim||"").trim();try{applyPhase(claim,S.T);if(S.entropy==null){qBell();qCollapse()}}catch(e){}var eqs=computeEQS(claim),ma=mathAnswer(claim),dec="REVIEW";if(eqs>=70&&S.phase!=="DISORDERED")dec="ALLOW";else if(eqs<45||S.phase==="DISORDERED")dec="BLOCK";if(ma)dec="ALLOW";S.lastGate=dec;var body={system:"AKSI-UNITY-v8",claim:claim,decision:dec,eqs:eqs,phase:S.phase,math:ma||null,did:S.did,ts:new Date().toISOString()};body.signature=await signPayload(body);set("trace",dec+" · EQS "+eqs+" · φ "+S.phase);var out=$("out");if(out){out.className="msg "+(dec==="ALLOW"?"allow":dec==="BLOCK"?"block":"");out.innerHTML="<span class=\"pill "+(dec==="ALLOW"?"ok":dec==="BLOCK"?"bad":"warn")+"\">"+dec+"</span>"+(ma?"<div class=\"meta\">"+ma.replace(/\n/g," · ")+"</div>":"")}paintTop();W.gate=dec;try{localStorage.setItem("aksi_unity_last",JSON.stringify(body))}catch(e){}return body}
function worldInit(){W.pts=[];for(var i=0;i<36;i++)W.pts.push({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.004,vy:(Math.random()-.5)*.004})}
function worldFrame(){var c=$("worldC");if(!c||!c.getContext)return;var ctx=c.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth||360,h=220;c.width=(w*dpr)|0;c.height=(h*dpr)|0;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#05010f";ctx.fillRect(0,0,w,h);var sp=1+(S.entropy||0)*.4,col=W.gate==="ALLOW"?"#34d399":W.gate==="BLOCK"?"#f87171":"#818cf8";W.pts.forEach(function(p){p.x+=p.vx*sp;p.y+=p.vy*sp;if(p.x<0||p.x>1)p.vx*=-1;if(p.y<0||p.y>1)p.vy*=-1;ctx.beginPath();ctx.fillStyle=col;ctx.globalAlpha=.75;ctx.arc(p.x*w,p.y*h,2.5,0,6.28);ctx.fill()});ctx.globalAlpha=1;if(document.querySelector('.panel.on[data-p="world"]'))requestAnimationFrame(worldFrame)}
async function linkAll(){var claim=($("claim")&&$("claim").value)||($("chatIn")&&$("chatIn").value)||"2+2";applyPhase(claim,S.T);qBell();qCollapse();computeEQS(claim);await runGate(claim);go("home")}
function boot(){if(_booted)return;_booted=1;document.querySelectorAll(".bnav button").forEach(function(b){b.addEventListener("click",function(){go(b.getAttribute("data-go"))})});document.querySelectorAll("[data-jump]").forEach(function(b){b.addEventListener("click",function(){go(b.getAttribute("data-jump"))})});var h=(location.hash||"").replace("#","");if(h)go(h);else go("chat");ensureDid();qInit();worldInit();if($("btnLinkAll"))$("btnLinkAll").onclick=function(){linkAll()};var ts=$("tempSlider");if(ts)ts.oninput=function(){S.T=parseFloat(ts.value)||1.2;set("phT",S.T.toFixed(3))};if($("btnPhase"))$("btnPhase").onclick=function(){_dc=null;applyPhase(($("phaseIn")&&$("phaseIn").value)||"aksi",S.T)};if($("btnScan"))$("btnScan").onclick=function(){_dc=null;drawPhaseChart()};if($("qInit"))$("qInit").onclick=qInit;if($("qH"))$("qH").onclick=qAllH;if($("qEntangle"))$("qEntangle").onclick=qBell;if($("qCollapse"))$("qCollapse").onclick=qCollapse;if($("wPulse"))$("wPulse").onclick=function(){go("world");worldFrame()};if($("wReset"))$("wReset").onclick=worldInit;if($("algoRun"))$("algoRun").onclick=function(){computeEQS(($("algoIn")&&$("algoIn").value)||"")};if($("btnRun"))$("btnRun").onclick=function(){runGate(($("claim")&&$("claim").value)||"")};if($("btnClear"))$("btnClear").onclick=function(){if($("claim"))$("claim").value="";set("trace","—");if($("out")){$("out").className="msg";$("out").textContent="—"}};if($("btnRotate"))$("btnRotate").onclick=function(){S.did=null;S._priv=null;ensureDid()};if($("btnVerify"))$("btnVerify").onclick=function(){try{var o=JSON.parse(($("verifyBox")&&$("verifyBox").value)||"{}");set("verifyOut",o.decision?"OK "+o.decision:"—")}catch(e){set("verifyOut","JSON error")}};if($("btnChat"))$("btnChat").onclick=sendChat;if($("chatIn"))$("chatIn").addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendChat()}});applyPhase("АКСИ",S.T);appendChat("aksi","Math online · "+mskNow()+"\n2+2*3 · sqrt(2) · x^2-4=0 · 15% от 80");setInterval(paintTop,1000);paintTop()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
window.AKSIUnity={mathAnswer:mathAnswer,evalExpr:evalExpr,chatRespond:chatRespond,state:function(){return S}};
})();
