/** AKSI Super Fabric v2.2 — mind via answer() */
(function(G){"use strict";
var VERSION="super-2.2.0",MEM_KEY="aksi_super_mem_v2";
function now(){return Date.now()}
function uid(p){return (p||"job")+"_"+now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
function hashStr(s){var h=2166136261>>>0,t=String(s),i;for(i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return ("00000000"+(h>>>0).toString(16)).slice(-8)}
async function sha256(text){if(!G.crypto||!G.crypto.subtle)return hashStr(text)+hashStr(text+"x");var buf=new TextEncoder().encode(String(text));var dig=await G.crypto.subtle.digest("SHA-256",buf);return Array.from(new Uint8Array(dig)).map(function(b){return ("0"+b.toString(16)).slice(-2)}).join("")}
function matMul(n){n=Math.min(Math.max(n||32,8),96);var a=new Float64Array(n*n),b=new Float64Array(n*n),c=new Float64Array(n*n),i,j,k,s,t0=performance.now();for(i=0;i<n*n;i++){a[i]=Math.sin(i*0.017)*0.5;b[i]=Math.cos(i*0.013)*0.5}for(i=0;i<n;i++)for(j=0;j<n;j++){s=0;for(k=0;k<n;k++)s+=a[i*n+k]*b[k*n+j];c[i*n+j]=s}var ms=performance.now()-t0,checksum=0;for(i=0;i<c.length;i+=7)checksum+=c[i];return{n:n,ms:ms,checksum:checksum,flops:2*n*n*n}}
function quantumCollapse(seedText){var n=4,dim=1<<n,hv=2166136261>>>0,s=String(seedText),i;for(i=0;i<s.length;i++){hv^=s.charCodeAt(i);hv=Math.imul(hv,16777619)}var sv=new Float64Array(dim*2);sv[0]=1;
function applyH(q){var inv=Math.SQRT1_2,step=1<<q,out=new Float64Array(sv),base,i0,i1,a0r,a0i,a1r,a1i;for(base=0;base<dim;base+=step<<1)for(i=0;i<step;i++){i0=base+i;i1=base+i+step;a0r=sv[2*i0];a0i=sv[2*i0+1];a1r=sv[2*i1];a1i=sv[2*i1+1];out[2*i0]=inv*(a0r+a1r);out[2*i0+1]=inv*(a0i+a1i);out[2*i1]=inv*(a0r-a1r);out[2*i1+1]=inv*(a0i-a1i)}sv=out}
function applyRY(q,theta){var c=Math.cos(theta/2),si=Math.sin(theta/2),step=1<<q,out=new Float64Array(sv),base,i0,i1,a0r,a0i,a1r,a1i;for(base=0;base<dim;base+=step<<1)for(i=0;i<step;i++){i0=base+i;i1=base+i+step;a0r=sv[2*i0];a0i=sv[2*i0+1];a1r=sv[2*i1];a1i=sv[2*i1+1];out[2*i0]=c*a0r-si*a1r;out[2*i0+1]=c*a0i-si*a1i;out[2*i1]=si*a0r+c*a1r;out[2*i1+1]=si*a0i+c*a1i}sv=out}
for(i=0;i<n;i++){applyH(i);applyRY(i,((hv>>>(i*5))%1000)/1000*Math.PI)}
var p=new Float64Array(dim),sum=0,e=0;for(i=0;i<dim;i++){p[i]=sv[2*i]*sv[2*i]+sv[2*i+1]*sv[2*i+1];sum+=p[i]}for(i=0;i<dim;i++)if(p[i]>1e-15)e-=p[i]*Math.log(p[i])/Math.LN2;
var r=Math.random(),acc=0,idx=dim-1;for(i=0;i<dim;i++){acc+=p[i];if(r<=acc){idx=i;break}}
return{bits:("0000"+idx.toString(2)).slice(-4),idx:idx,entropy:e,sumP:sum,seed:hv>>>0}}
function SuperFabric(opts){opts=opts||{};this.nodes=[];this.queue=[];this.running=[];this.done=[];this.stats={jobs:0,flops:0,ms:0,mem_bytes:0,pipelines:0,allows:0,blocks:0};this.memory=[];this.maxMem=opts.maxMem||8000;this.booted=false;this._tick=null;this.exo=null;this.goal=null;this.onEvent=null}
SuperFabric.prototype.emit=function(stage,detail){var ev={t:now(),stage:stage,detail:detail};if(typeof this.onEvent==="function")try{this.onEvent(ev)}catch(e){}return ev};
SuperFabric.prototype.attachExocortex=async function(){var X=G.AKSI_EXOCORTEX;if(!X||!X.Exocortex){this.emit("exocortex",{ok:false,reason:"no exo"});return null}this.exo=new X.Exocortex();await this.exo.initKeys();this.emit("exocortex",{ok:true,version:X.version});return this.exo};
SuperFabric.prototype.boot=function(nodeCount,gpusPerNode){nodeCount=nodeCount||8;gpusPerNode=gpusPerNode||4;this.nodes=[];var i,j;for(i=0;i<nodeCount;i++){var gpus=[];for(j=0;j<gpusPerNode;j++)gpus.push({id:"gpu-"+i+"-"+j,util:0,temp:42+Math.random()*8,jobs:0});this.nodes.push({id:"node-"+i,rack:"R"+Math.floor(i/4),status:"online",gpus:gpus,load:0})}this.booted=true;this.remember("boot",{nodes:nodeCount,gpus:nodeCount*gpusPerNode});this.emit("boot",{nodes:nodeCount,gpus:nodeCount*gpusPerNode});return this.snapshot()};
SuperFabric.prototype.remember=function(kind,data){var entry={t:now(),kind:kind,data:data,h:hashStr(kind+JSON.stringify(data)+this.memory.length)};this.memory.push(entry);if(this.memory.length>this.maxMem)this.memory=this.memory.slice(-Math.floor(this.maxMem*0.8));this.stats.mem_bytes=this.memory.length*180;try{localStorage.setItem(MEM_KEY,JSON.stringify(this.memory.slice(-300)))}catch(e){}return entry};
SuperFabric.prototype.loadMemory=function(){try{var raw=localStorage.getItem(MEM_KEY);if(raw)this.memory=JSON.parse(raw)||[]}catch(e){this.memory=[]}this.stats.mem_bytes=this.memory.length*180};
SuperFabric.prototype.setGoal=function(goal){this.goal=String(goal||"").slice(0,4000);this.remember("goal",{text:this.goal});this.emit("goal",{text:this.goal});if(this.exo)try{this.exo.setGoal(this.goal)}catch(e){}return this.goal};
SuperFabric.prototype.observe=function(text){this.remember("observe",{text:String(text).slice(0,2000)});if(this.exo)try{return this.exo.observe(text)}catch(e){}return{text:text}};
SuperFabric.prototype.submit=function(job){job=job||{};var j={id:uid("job"),type:job.type||"matmul",size:job.size||48,prompt:job.prompt||"",status:"queued",node:null,gpu:null,created:now(),started:null,finished:null,result:null,quantum:null,receipt:null,stages:[]};this.queue.push(j);this.remember("submit",{id:j.id,type:j.type});this.emit("submit",{id:j.id,type:j.type});return j};
SuperFabric.prototype._pickGpu=function(){var best=null,i,j,g,score;for(i=0;i<this.nodes.length;i++){if(this.nodes[i].status!=="online")continue;for(j=0;j<this.nodes[i].gpus.length;j++){g=this.nodes[i].gpus[j];score=g.util+g.jobs*0.1;if(!best||score<best.score)best={score:score,node:this.nodes[i],gpu:g}}}return best};
SuperFabric.prototype._stage=function(job,name,data){job.stages.push({name:name,t:now(),data:data});this.emit("stage",{job:job.id,name:name,data:data})};
SuperFabric.prototype._runJob=function(job){var self=this,pick=this._pickGpu();if(!pick){job.status="queued";return null}job.status="running";job.started=now();job.node=pick.node.id;job.gpu=pick.gpu.id;pick.gpu.util=Math.min(100,pick.gpu.util+35+Math.random()*40);pick.gpu.temp=Math.min(92,(pick.gpu.temp||45)+5);pick.gpu.jobs+=1;pick.node.load=pick.node.gpus.reduce(function(a,g){return a+g.util},0)/pick.node.gpus.length;this.running.push(job);this.queue=this.queue.filter(function(x){return x.id!==job.id});
return new Promise(function(resolve){setTimeout(async function(){try{var q=quantumCollapse(job.id+"|"+job.type+"|"+(job.prompt||self.goal||""));job.quantum=q;self._stage(job,"quantum",{bits:q.bits,S:q.entropy,sumP:q.sumP});var result={};
if(job.type==="mind"||job.type==="ask"){
  var Mind=G.AKSI_SUPER_MIND;
  var mm0=matMul(Math.min(job.size||32,40));
  self.stats.flops+=mm0.flops;self.stats.ms+=mm0.ms;
  self._stage(job,"compute",{flops:mm0.flops,ms:mm0.ms,mind:true});
  var syn;
  if(Mind&&Mind.answer){syn=await Mind.answer(job.prompt||self.goal||"",q);}
  else if(Mind&&Mind.synthesize){syn=Mind.synthesize(job.prompt||self.goal||"",q);syn.source="mind";}
  else {syn={text:"Модуль Mind не загружен. Обновите страницу.",path:0,source:"none"};}
  self._stage(job,"mind",{path:syn.path,topics:syn.topics,hasMath:!!(syn.math&&syn.math.ok),source:syn.source||"mind"});
  var payloadM=(job.prompt||"").slice(0,400);
  var permitStatus="ALLOW",permitReason="OK",receipt=null;
  if(self.exo){var step=await self.exo.step("report",payloadM+" |mind|"+q.bits);permitStatus=step.status;permitReason=step.permit&&step.permit.reason;receipt=step.receipt;self._stage(job,"permit",{status:permitStatus,reason:permitReason});self._stage(job,"receipt",{id:receipt&&receipt.id?receipt.id.slice(0,16):null});if(permitStatus==="ALLOW")self.stats.allows+=1;else self.stats.blocks+=1;}
  else {self.stats.allows+=1;self._stage(job,"permit",{status:"ALLOW",reason:"NO_EXO"});}
  result={kind:"mind",report:syn.text,answer:syn.text,permit:permitStatus,receipt_id:receipt&&receipt.id,quantum:q,math:syn.math||null,source:syn.source||"mind"};
  job.receipt=receipt;self.stats.pipelines+=1;self.remember("mind",{id:job.id,path:syn.path,permit:permitStatus,source:syn.source});
}else if(job.type==="pipeline"||job.type==="full"){self._stage(job,"plan",{goal:self.goal||job.prompt});var mm=matMul(job.size||48);self.stats.flops+=mm.flops;self.stats.ms+=mm.ms;self._stage(job,"compute",{flops:mm.flops,ms:mm.ms,checksum:mm.checksum});
var payload=(self.goal||job.prompt||"pipeline").slice(0,500),permitStatus="ALLOW",permitReason="OK",receipt=null;
if(self.exo){var step=await self.exo.step("report",payload+" |Q:"+q.bits);permitStatus=step.status;permitReason=step.permit&&step.permit.reason;receipt=step.receipt;self._stage(job,"permit",{status:permitStatus,reason:permitReason});self._stage(job,"receipt",{id:receipt&&receipt.id?receipt.id.slice(0,16):null});if(permitStatus==="ALLOW")self.stats.allows+=1;else self.stats.blocks+=1}
else{if(/spend|delete|exfiltrate/i.test(payload)){permitStatus="BLOCK";permitReason="LOCAL_DENY";self.stats.blocks+=1}else self.stats.allows+=1;var body={v:VERSION,t:new Date().toISOString(),action:"report",payload:payload,quantum:q,prev:self.done.length?self.done[0].id:"GENESIS"};var id=await sha256(JSON.stringify(body));body.id=id;body.signature=hashStr(id+q.bits);receipt=body;self._stage(job,"permit",{status:permitStatus,reason:permitReason});self._stage(job,"receipt",{id:id.slice(0,16),local:true})}
var report=["PIPELINE REPORT","goal: "+(self.goal||job.prompt||"—"),"quantum: |"+q.bits+"⟩","permit: "+permitStatus,"receipt: "+(receipt&&receipt.id?receipt.id.slice(0,24):"—")].join("\n");
result={kind:"pipeline",report:report,permit:permitStatus,receipt_id:receipt&&receipt.id,quantum:q};job.receipt=receipt;self.stats.pipelines+=1;}
else if(job.type==="matmul"||job.type==="ai_train"||job.type==="gpu_batch"){var m=matMul(job.size);self.stats.flops+=m.flops;result={kind:job.type,flops:m.flops,ms:m.ms};}
else if(job.type==="quantum"){result={kind:"quantum",bits:q.bits,entropy:q.entropy};}
else if(job.type==="memory_scan"){result={kind:"memory_scan",entries:self.memory.length};}
else{var m2=matMul(Math.min(job.size||32,40));self.stats.flops+=m2.flops;result={kind:job.type,flops:m2.flops};}
job.result=result;job.status="done";job.finished=now();pick.gpu.util=Math.max(0,pick.gpu.util-25);pick.node.load=pick.node.gpus.reduce(function(a,g){return a+g.util},0)/pick.node.gpus.length;self.running=self.running.filter(function(x){return x.id!==job.id});self.done.unshift(job);if(self.done.length>80)self.done=self.done.slice(0,80);self.stats.jobs+=1;self.remember("done",{id:job.id,type:job.type,quantum:q.bits});self._stage(job,"done",{status:"done"});resolve(job);
}catch(err){job.status="error";job.result={error:String(err&&err.message||err)};job.finished=now();self.running=self.running.filter(function(x){return x.id!==job.id});self.done.unshift(job);self.emit("error",{job:job.id,error:job.result.error});resolve(job);}},60+Math.random()*180);});};
SuperFabric.prototype.tick=function(){var self=this,promises=[],maxRun=Math.max(2,Math.floor(this.nodes.length/2));while(this.queue.length&&this.running.length<maxRun){var p=this._runJob(this.queue[0]);if(p)promises.push(p);else break}this.nodes.forEach(function(n){n.gpus.forEach(function(g){if(g.util>0)g.util=Math.max(0,g.util-2);if(g.temp>42)g.temp=Math.max(42,g.temp-0.4)});n.load=n.gpus.reduce(function(a,g){return a+g.util},0)/n.gpus.length});return Promise.all(promises)};
SuperFabric.prototype.startScheduler=function(ms){var self=this;if(this._tick)clearInterval(this._tick);this._tick=setInterval(function(){self.tick();if(typeof self.onTick==="function")try{self.onTick(self.snapshot())}catch(e){}},ms||350)};
SuperFabric.prototype.stopScheduler=function(){if(this._tick)clearInterval(this._tick);this._tick=null};
SuperFabric.prototype.runFull=async function(goalText){if(!this.booted)this.boot(8,4);if(!this._tick)this.startScheduler(300);if(!this.exo)try{await this.attachExocortex()}catch(e){}if(goalText)this.setGoal(goalText);this.observe("user_goal:"+(goalText||this.goal||""));var job=this.submit({type:"pipeline",size:48,prompt:goalText||this.goal||"full"});var self=this;return new Promise(function(resolve){var t0=now(),iv=setInterval(function(){var found=self.done.find(function(j){return j.id===job.id});if(found||now()-t0>15000){clearInterval(iv);resolve(found||job)}},100)})};
SuperFabric.prototype.snapshot=function(){var gpus=0,util=0;this.nodes.forEach(function(n){n.gpus.forEach(function(g){gpus+=1;util+=g.util})});return{version:VERSION,booted:this.booted,goal:this.goal,exo:!!this.exo,nodes:this.nodes.length,gpus:gpus,avg_util:gpus?util/gpus:0,queue:this.queue.length,running:this.running.length,done:this.done.length,stats:Object.assign({},this.stats),mem_entries:this.memory.length,nodes_detail:this.nodes,recent:this.done.slice(0,6)}};
SuperFabric.prototype.exportJSON=function(){return{version:VERSION,snapshot:this.snapshot(),memory_tail:this.memory.slice(-80),done_tail:this.done.slice(0,40)}};
SuperFabric.prototype.verifyExoChain=async function(){if(!this.exo)return{ok:false,reason:"no exo"};return this.exo.verifyChain()};
G.AKSI_SUPER={version:VERSION,SuperFabric:SuperFabric,matMul:matMul,quantumCollapse:quantumCollapse,hashStr:hashStr};
})(typeof window!=="undefined"?window:globalThis);
