/**
 * AKSI FIR — Full Intelligence Runtime v2.0
 * PLAN → RETRIEVE → EVIDENCE → GENERATE/FUSE → VERIFY → Q-GATE → ADIA → LEARN → ATTEST
 * Internet is an untrusted evidence layer, not an authority.
 */
(function(G){
'use strict';
var VER='2.0.0-fir-evidence',TRACE_KEY='aksi_fir_trace_v2',MEM_KEY='aksi_fir_memory_v2';
function now(){return Date.now();} function uid(){return 'fir'+now().toString(36)+Math.random().toString(36).slice(2,6);} function round(x,d){var p=Math.pow(10,d==null?3:d);return Math.round(Number(x||0)*p)/p;}
function load(k){try{var a=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(a)?a:[];}catch(e){return [];}} function save(k,a){try{localStorage.setItem(k,JSON.stringify(a.slice(-100)));}catch(e){}}
function plan(q){var s=String(q||'').trim(),l=s.toLowerCase();return{raw:s,teach:/^\s*(запомни|remember|learn)\s*[:：]/i.test(s),wantLlm:/подробн|развёрн|разверн|explain|код/.test(l),lang:/[а-яё]/i.test(s)?'ru':'en'};}
function callNeuro(q){try{var n=G.AKSI_NEURO;if(n&&n.think){var r=n.think(q);if(r&&(r.text||r.answer))return{text:String(r.text||r.answer),source:'neuro',score:r.score==null?.70:r.score};}if(n&&n.ask){var a=n.ask(q);if(a)return{text:String(a.text||a),source:'neuro',score:.65};}}catch(e){}return null;}
function callMind(q){try{var m=G.AKSI_MIND_L2||G.AKSI_MIND;if(m&&m.think){var r=m.think(q);if(r&&r.text)return{text:String(r.text),source:'mind',score:.60};}}catch(e){}return null;}
async function callModule(name,q,score){try{var m=G[name];if(m&&m.think){var r=await m.think(q),p=r&&r.payload||r;if(p&&p.answer)return{text:String(p.answer),source:name.toLowerCase(),score:score||.5,raw:r,seal:r&&r.seal,quantum:p.quantum};}}catch(e){}return null;}
async function callWebLLM(q){try{var w=G.AKSI_WEBLLM;if(w&&w.ready&&w.ready()){var r=await w.complete(q,{system:'Ты АКСИ. Интернет — источник доказательств, а не авторитет. Не выдумывай факты.'});if(r&&r.text)return{text:r.text,source:'webllm',score:.85,model:r.model};}}catch(e){}return null;}
async function ensureEvidence(){if(G.AKSI_WEB_EVIDENCE)return G.AKSI_WEB_EVIDENCE;try{await new Promise(function(resolve,reject){var s=document.createElement('script');s.src='/aksi-web-evidence.js?v=1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}catch(e){}return G.AKSI_WEB_EVIDENCE||null;}
function overlap(a,b){var q=String(a||'').toLowerCase().split(/\s+/).filter(function(x){return x.length>3;}),t=String(b||'').toLowerCase(),h=0;q.forEach(function(w){if(t.indexOf(w)>=0)h++;});return q.length?h/q.length:0;}
function claims(text){return String(text||'').split(/(?<=[.!?])\s+/).map(function(x){return x.trim();}).filter(function(x){return x.length>25;}).slice(0,12);}
async function digest(s){try{if(G.crypto&&G.crypto.subtle){var b=await G.crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(s)));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,'0');}).join('');}}catch(e){}return null;}
function fuse(cands){var best=null,second=null;cands.forEach(function(c){if(!c||!c.text)return;if(!best||c.score>best.score)best=c;});cands.forEach(function(c){if(c&&c.text&&c!==best&&(!second||c.score>second.score))second=c;});if(!best)return null;var text=best.text;if(second&&second.text&&!text.includes(second.text.slice(0,40)))text+='\n\n— Дополнительная опора: —\n'+second.text.slice(0,240);return{text:text,source:best.source+(second?'+'+second.source:''),score:best.score,primary:best,secondary:second};}
function teach(f){var a=load(MEM_KEY);a.push({id:uid(),text:f,ts:now(),provenance:'user'});save(MEM_KEY,a);try{if(G.AKSI_GENESIS&&G.AKSI_GENESIS.teach)G.AKSI_GENESIS.teach(f);if(G.AKSI_NEURO&&G.AKSI_NEURO.teach)G.AKSI_NEURO.teach(f);}catch(e){}return a.length;}
async function think(input,opts){opts=opts||{};var t0=now(),p=plan(input),steps=[];function step(s,d){steps.push({s:s,t:now()-t0,detail:d||null});}
if(!p.raw)return{answer:'Пустой запрос',source:'fir',thought:steps};step('plan',{internet:opts.internet!==false,teach:p.teach});
if(p.teach){var n=teach(p.raw.replace(/^\s*(запомни|remember|learn)\s*[:：]\s*/i,''));step('learn',{n:n});return{version:VER,answer:'Обучено. Память: '+n,source:'fir-learn',thought:steps};}
var cands=[],web=null;if(opts.internet!==false){var E=await ensureEvidence();if(E&&E.search){try{web=await E.search(p.raw,{research:opts.research!==false,refresh:!!opts.refreshWeb});step('retrieve',{providers:web.providers,sources:web.sources.length});}catch(e){step('retrieve-error',String(e.message||e));}}}
var n1=callNeuro(p.raw);if(n1)cands.push(n1);var m=callMind(p.raw);if(m)cands.push(m);var g=await callModule('AKSI_GENESIS',p.raw,.55);if(g)cands.push(g);var ai=await callModule('AKSI_AI',p.raw,.55);if(ai)cands.push(ai);
var best=cands.reduce(function(x,c){return Math.max(x,c.score||0);},0);if(opts.useWebLLM!==false&&(p.wantLlm||best<.45||opts.forceLlm)){var l=await callWebLLM(p.raw);if(l)cands.push(l);}
if(web&&web.sources&&web.sources.length){var evidenceText=web.sources.slice(0,5).map(function(s){return s.title+'\n'+s.summary;}).join('\n\n');cands.push({text:evidenceText,source:'web-evidence',score:.82,evidence:web.sources});}
load(MEM_KEY).forEach(function(x){if(overlap(p.raw,x.text)>.2)cands.push({text:x.text,source:'memory',score:.56,evidence:[{title:'AKSI local memory',url:'local://memory',summary:x.text}]});});
var fused=fuse(cands);step('fuse',{candidates:cands.length,pick:fused&&fused.source});if(!fused){fused={text:p.lang==='ru'?'Недостаточно проверяемой опоры.':'Insufficient verifiable support.',source:'fir-gap',score:.2};step('gap');}
var cls=claims(fused.text),claimRecords=[];for(var i=0;i<cls.length;i++){var support=web&&web.sources?web.sources.map(function(s){return overlap(cls[i],s.summary);}).filter(function(x){return x>.15;}):[];claimRecords.push({text:cls[i],support:support.length,confidence:round(Math.min(1,.25+.18*support.length),3),hash:await digest(cls[i])});}step('verify',{claims:claimRecords.length,supported:claimRecords.filter(function(x){return x.support>0;}).length});
var quantum=null;if(G.AKSI_QPIPE&&G.AKSI_QPIPE.processAnswer){try{quantum=await G.AKSI_QPIPE.processAnswer(p.raw,fused.text);step('qpipe');}catch(e){}}
var adia=null;try{var AD=G.AKSI_ADIA||G.ADIA||G.AKSI_ALGORITHM;if(AD&&AD.evaluate)adia=AD.evaluate({query:p.raw,answer:fused.text});else if(AD&&AD.process)adia=AD.process({query:p.raw,answer:fused.text});step('adia');}catch(e){}
var body={id:uid(),version:VER,input:p.raw,answer:fused.text,source:fused.source,score:round(fused.score),internet:!!web,retrieval:web&&{providers:web.providers,count:web.sources.length,retrievedAt:web.retrievedAt},evidence:web&&web.sources||[],claims:claimRecords,layers:cands.map(function(c){return{source:c.source,score:round(c.score),preview:String(c.text).slice(0,80)};}),quantum:quantum,adia:adia,thought:steps,ms:now()-t0};body.answerHash=await digest(JSON.stringify(body));
if(G.AKSI_CRYPTO&&G.AKSI_CRYPTO.sealJson){try{var sealed=await G.AKSI_CRYPTO.sealJson(body);body.seal=sealed.seal||sealed;step('attest');}catch(e){step('attest-error',String(e.message||e));}}
save(TRACE_KEY,load(TRACE_KEY).concat([{id:body.id,ts:t0,answerHash:body.answerHash,sources:body.evidence.length}]));return{payload:body,answer:body.answer,source:body.source,thought:body.thought,seal:body.seal,layers:body.layers,evidence:body.evidence,claims:body.claims,ms:body.ms};}
async function status(){var e=G.AKSI_WEB_EVIDENCE;return{version:VER,internetEvidence:!!e,neuro:!!G.AKSI_NEURO,genesis:!!(G.AKSI_GENESIS&&G.AKSI_GENESIS.think),webllm:!!G.AKSI_WEBLLM,qpipe:!!G.AKSI_QPIPE,crypto:!!G.AKSI_CRYPTO,adia:!!(G.AKSI_ADIA||G.AKSI_ALGORITHM),memory:load(MEM_KEY).length};}
G.AKSI_FIR={version:VER,think:think,status:status,teach:function(f){return{ok:true,n:teach(String(f||''))};},memory:function(){return load(MEM_KEY);},layers:['plan','internet-evidence','neuro','mind','genesis','aksi-ai','webllm','verify','qpipe','adia','crypto']};
if(G.AKSIAgent&&G.AKSIAgent.ask){var old=G.AKSIAgent.ask;G.AKSIAgent.ask=async function(q,o){if(o&&o.skipFir)return old.call(G.AKSIAgent,q,o);try{var r=await think(q,o),p=r.payload||r;return{text:p.answer||r.answer,source:p.source||'fir',offline:false,internet:!!p.internet,critique:{score:p.score},evidence:p.evidence,claims:p.claims,seal:p.seal,thought:p.thought,layers:p.layers,ms:p.ms};}catch(e){return old.call(G.AKSIAgent,q,o);}};}
})(typeof window!=='undefined'?window:globalThis);
