(()=>{'use strict';
/* AKSI PROOF LEDGER — transparent local evidence receipts. No fake verification. */
const KEY='AKSI_PROOF_LEDGER_V1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digest=async s=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const put=x=>localStorage.setItem(KEY,JSON.stringify(x.slice(-100)));
async function add(type,payload){const prev=get().at(-1)?.hash||'GENESIS';const record={id:crypto.randomUUID(),type,payload,previous_hash:prev,created_at:new Date().toISOString()};record.hash=await digest(JSON.stringify(record));const all=get();all.push(record);put(all);render();return record}
function mount(){if(document.querySelector('[data-proof-root]'))return;const host=document.querySelector('[data-view="trust"]')||document.querySelector('[data-view="home"]');if(!host)return;const box=document.createElement('section');box.className='proof-ledger';box.dataset.proofRoot='1';box.innerHTML='<div class="eyebrow">AKSI PROOF LEDGER</div><h2>Проверяемость, а не обещания</h2><p>Каждая запись получает собственный хэш и ссылку на предыдущую запись. Это локальный журнал: он не доказывает, что внешнее утверждение истинно — он доказывает, что запись не была тихо изменена внутри журнала.</p><div class="proof-actions"><button id="proofTest">Создать тестовую запись</button><button id="proofVerify">Проверить цепочку</button><button id="proofExport">Экспортировать журнал</button></div><div id="proofStatus" class="proof-status">LEDGER READY · GENESIS</div><div id="proofRows"></div>';host.appendChild(box);box.querySelector('#proofTest').onclick=()=>add('TEST',{message:'AKSI integrity test'});box.querySelector('#proofVerify').onclick=verify;box.querySelector('#proofExport').onclick=exportLog;render()}
async function verify(){const all=get();let prev='GENESIS';let ok=true;for(const r of all){if(r.previous_hash!==prev||r.hash!==await digest(JSON.stringify({id:r.id,type:r.type,payload:r.payload,previous_hash:r.previous_hash,created_at:r.created_at})))ok=false;prev=r.hash}const s=document.getElementById('proofStatus');if(s)s.textContent=(ok?'✓ CHAIN INTACT · ':'✕ CHAIN BROKEN · ')+all.length+' RECORDS';return ok}
function render(){const root=document.getElementById('proofRows');if(!root)return;const all=get();root.innerHTML=all.slice(-8).reverse().map(r=>`<div class="proof-row"><b>${esc(r.type)}</b><span>${esc(r.created_at)}</span><code>${esc(r.hash.slice(0,24))}…</code></div>`).join('')||'<div class="proof-empty">Журнал пуст. Создай тестовую запись.</div>'}
function exportLog(){const blob=new Blob([JSON.stringify(get(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aksi-proof-ledger.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.AKSIProof={add,verify,history:get};document.addEventListener('DOMContentLoaded',mount);})();
