(()=>{'use strict';
const toast=(title,text)=>{let x=document.querySelector('.simple-toast');if(!x){x=document.createElement('div');x.className='simple-toast';document.body.appendChild(x)}x.innerHTML=`<b>${title}</b><span>${text}</span>`;x.classList.add('on');clearTimeout(window.__aksiToast);window.__aksiToast=setTimeout(()=>x.classList.remove('on'),3600)};
const updateClock=()=>{const el=document.querySelector('[data-wow-clock]');if(el)el.textContent=new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())};
const explain=()=>{if(document.querySelector('.simple-panel'))return;const home=document.querySelector('[data-view="home"]');if(!home)return;const panel=document.createElement('section');panel.className='simple-panel';panel.innerHTML='<div class="simple-kicker">Понятно без терминов</div><h2>АКСИ — это очень просто</h2><p>Ты задаёшь вопрос. АКСИ думает. Затем показывает, что известно, чего не хватает и что можно проверить.</p><div class="simple-steps"><div class="simple-step"><span class="num">01</span><b>💬 Спроси</b><span>Напиши обычными словами.</span></div><div class="simple-step"><span class="num">02</span><b>🧠 Подумай</b><span>АКСИ обрабатывает задачу.</span></div><div class="simple-step"><span class="num">03</span><b>🔐 Проверь</b><span>Посмотри запись и её хэш.</span></div><div class="simple-step"><span class="num">04</span><b>✨ Решай</b><span>Ты решаешь, доверять результату или проверить ещё раз.</span></div></div><div class="simple-action"><button class="primary" data-simple-go="chat">Попробовать сейчас →</button><button data-simple-go="trust">Узнать про проверку</button></div>';home.insertBefore(panel,home.children[1]||null)};
const simpleHelp=()=>{if(document.querySelector('.simple-help'))return;const b=document.createElement('button');b.className='simple-help';b.type='button';b.innerHTML='❔ <strong>Объяснить проще</strong>';b.onclick=()=>{document.querySelector('.simple-panel')?.scrollIntoView({behavior:'smooth',block:'center'});toast('АКСИ','Сложные детали можно оставить системе.')};document.body.appendChild(b)};
const loadSimple=()=>{if(window.__aksiSimpleLoaded)return;window.__aksiSimpleLoaded=true;for(const src of ['/aksi-simple.js','/aksi-evidence.js']){const s=document.createElement('script');s.src=src;s.async=false;document.body.appendChild(s)}};
window.addEventListener('aksi:ready',()=>toast('АКСИ CORE','Готово. Можно задавать вопрос обычными словами.'));window.addEventListener('aksi:control-ready',()=>toast('СИСТЕМА ГОТОВА','Память и журнал подключены.'));window.addEventListener('aksi:quantum-ready',()=>toast('QUANTUM','Экспериментальный модуль готов.'));window.addEventListener('aksi:precedent',()=>toast('PRECEDENT','Вопрос зафиксирован без превращения догадки в факт.'));
document.addEventListener('click',e=>{const b=e.target.closest('[data-wow-action]');if(b){const a=b.dataset.wowAction;if(a==='proof')document.querySelector('[data-nav="trust"]')?.click();if(a==='chat')document.querySelector('[data-nav="chat"]')?.click()}const s=e.target.closest('[data-simple-go]');if(s){const target=s.dataset.simpleGo;document.querySelector(`[data-nav="${target}"]`)?.click()}});
for(const href of ['/aksi-simple.css','/aksi-proof.css']){const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
setInterval(updateClock,1000);updateClock();document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{explain();simpleHelp();loadSimple()}):(explain(),simpleHelp(),loadSimple());
})();