const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('aksi-runtime.js', 'utf8');
const context = { console, Date, Math };
context.window = context;
vm.createContext(context);
vm.runInContext(source, context, { filename: 'aksi-runtime.js' });
assert.ok(context.AKSI_RUNTIME);
assert.strictEqual(context.AKSI_RUNTIME.version, '1.0.0');
const degraded = context.AKSI_RUNTIME.selfTest();
assert.strictEqual(degraded.ok, false);
context.AKSI_CORE = { query() {} };
const ready = context.AKSI_RUNTIME.selfTest();
assert.strictEqual(ready.ok, true);
const answer = context.AKSI_RUNTIME.answer('q', 'a', { source:'core', kind:'computed', confidence:1.4, citations:['x','y'] });
assert.strictEqual(answer.schema, 'AKSI-ANSWER-1');
assert.strictEqual(answer.confidence, 1);
assert.deepStrictEqual(answer.citations, ['x','y']);
console.log('AKSI runtime contract tests: OK');
