const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
const source=fs.readFileSync('aksi-runtime.js','utf8');
const store=new Map();
const context={console,Date,Math,TextEncoder,Uint8Array,ArrayBuffer,crypto:webcrypto,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},CustomEvent:function(type,init){this.type=type;this.detail=init&&init.detail},dispatchEvent:()=>true};
context.window=context;vm.createContext(context);vm.runInContext(source,context,{filename:'aksi-runtime.js'});
(async()=>{assert.ok(context.AKSI_RUNTIME);assert.strictEqual(context.AKSI_RUNTIME.version,'2.2.0');
context.AKSI_VERIFIER={verify:(answer,evidence)=>({version:'test',claim_count:1,supported:1,partial:0,unsupported:0,coverage:1,claims:[{claim:answer,status:'SUPPORTED',support:1,evidence_index:0}]})};
context.AKSI_STACK={decide:async(q)=>({ok:true,answer:'Результат '+q,best:{text:'Результат '+q,source:'test',evidence:[{text:'Результат '+q}]},gate:{decision:'ALLOW',reason:'test'},candidates:1,adia:{version:'test'}})};
const st=await context.AKSI_RUNTIME.selfTest();assert.strictEqual(st.ok,true);assert.strictEqual(st.sha256,true);
const a=await context.AKSI_RUNTIME.execute('hello',{save:true});assert.strictEqual(a.schema,'AKSI-RESULT-2');assert.strictEqual(a.answer,'Результат hello');assert.strictEqual(a.gate.decision,'ALLOW');assert.strictEqual(a.receipt.hash.length,64);assert.strictEqual(a.verification.supported,1);assert.strictEqual(context.AKSI_RUNTIME.memory().length,1);assert.strictEqual(context.AKSI_RUNTIME.receipts().length,1);
const x={b:2,a:'AKSI',u:undefined},y={a:'AKSI',b:2};assert.strictEqual(context.AKSI_RUNTIME.canonical(x),context.AKSI_RUNTIME.canonical(y));assert.strictEqual(await context.AKSI_RUNTIME.sha256(x),await context.AKSI_RUNTIME.sha256(y));
context.AKSI_STACK={decide:async()=>({answer:'second',best:{text:'second',source:'test2'},gate:{decision:'DEFER'},candidates:2,adia:{version:'test2'}})};
const b=await context.AKSI_RUNTIME.execute('second');assert.strictEqual(b.gate.decision,'DEFER');assert.strictEqual(b.receipt.hash.length,64);console.log('AKSI runtime contract tests: OK')})().catch(e=>{console.error(e);process.exitCode=1});