const assert=require('assert'),fs=require('fs');
const html=fs.readFileSync('world/index.html','utf8');
for(const s of ['AKSI Runtime','agentGoal','/api/agent/tasks','AKSI_RUNTIME','/aksi-runtime.js','/superpose/']) assert.ok(html.includes(s), 'missing '+s);
assert.ok(fs.existsSync('aksi-runtime.js'));
assert.ok(fs.existsSync('README_AKSI_WORLD.md'));
assert.ok(html.includes('Не AGI') || html.includes('Не новый foundation model'));
assert.ok(html.includes('Browser Actions'));
assert.ok(html.includes('/api/agent/browser/sessions'));
assert.ok(html.includes('/api/core/tasks/'));
console.log('AKSI World surface test: OK');